### ISSUE TITLE
Landing page content - short term

### ISSUE THREAD

**Issue by draggett** [w3c/wot-marketing#1]
I am unclear what people want in the short term for the landing page at 
* https://www.w3.org/WoT/
I've commented out the info on the Community Group and dropped the information on meetings.

**Comment by egekorkan** [comment]
@draggett will add a "Join Interest Group" button under the main column, specifically after this:

> The Web of Things Interest Group brings together stakeholders interested in the Web of Things to explore ideas prior to standardization together with collaboration with external groups, e.g. standards development organisations and industry alliances. The Interest Group is preparing to re-charter and we expect an AC Review shortly.

**Comment by danielpeintner** [comment]
Since the new website is due to go online shortly, short term points are no longer relevant.

@draggett please reopen if you think differently
