### ISSUE TITLE
Add W3C WoT in awesome IoT repository

### ISSUE THREAD

**Issue by relu91** [w3c/wot-marketing#103]
Awesome repositories are a series of curated lists of particular technologies. Of course, there is a repo dedicated to IoT technology. They have a section about [IoT standards](https://github.com/HQarroum/awesome-iot#standards), should we add W3C WoT? if yes please let me know I can create the PR.

**Comment by danielpeintner** [comment]
I think adding WoT to the list makes perfect sense to me!

**Comment by sebastiankb** [comment]
@relu91 would be create if you can provide a PR there

**Comment by relu91** [comment]
Sure!

**Comment by sebastiankb** [comment]
Please use the main entry page https://www.w3.org/WoT/ as link

**Comment by relu91** [comment]
https://github.com/HQarroum/awesome-iot/pull/70 ✔️

**Comment by sebastiankb** [comment]
thanks @relu91
