### ISSUE TITLE
TODOs from Marketing Call 2020-01-26

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#109]
- [x] add dates to Events on Activities page
  - added dates, see https://github.com/w3c/wot-marketing/commit/92c3526260151b16853bd04b47a1d6044c48c811. Still misses links 
- [X] rename "getting started" to  "documentation"
  - see PR https://github.com/w3c/wot-marketing/pull/110
- [ ] adding "tutorials" under "developers" navigation
  - @danielpeintner suggests to wait until we have content for tutorials
- [x] Video options, make proposals where to place it
  - first proposal see PR https://github.com/w3c/wot-marketing/pull/111

**Comment by egekorkan** [comment]
Item 3 can be tracked in #79, closing
