### ISSUE TITLE
Content of the getting started / Documentation page

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#115]
I think, this a very important page which different user should get first class information. My proposed structure would be:

1. Web of Things in a nutshell
Here we should have a nice illustration of a classical IoT scenario (heterogeneous IoT systems)  and how WoT would challenge this
2. Where to start
A couple of references should be provided to find tutorials about WoT (Ege) 
3. Decision makers 
We should provide a list of advantages of WoT that will have impact of IoT business. Here we can refer to success story of web. We can also include a link to the testimonials from the WoT press release.
4. Software developer and architects
Links to developer and tutorial space. 
5. Standardization activity
How to contribute to WoT (e.g., github, getting member etc.)

**Comment by danielpeintner** [comment]
is there anything missing in the latest update? https://w3c.github.io/wot-marketing/documentation/

I would say the content is not *all* on documentation page only but the content is generally __somewhere__ on the marketing website ...

**Comment by sebastiankb** [comment]
issue solved based on the new webpage
