### ISSUE TITLE
Plans for new WoT webpage launch on March 1st

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#118]
- The target date for the [new WoT welcome page](https://w3c.github.io/wot-marketing/) should be March 1st, 2021.
- A rehearsal should take place on February 26th, 2021.
- In the meantime we have to clarify the contents and old existing webpages hosted at w3c side (@danielpeintner provide details of the current discussion with @koalie, see [here](https://github.com/w3c/wot-marketing/issues/118#issuecomment-776688856))
- In addition, we will call the WoT group to review the current status of the new web page and provide feedback.

**Comment by danielpeintner** [comment]
## Existing content under https://www.w3.org/WoT/

> https://www.w3.org/WoT/demos/rdf/
> https://www.w3.org/WoT/demos/shrl/
> https://www.w3.org/WoT/demos/td2ttl/
> https://www.w3.org/WoT/talks/2016-04-27.pdf

@draggett suggest to keep them as is as a historic record of early work.

> https://www.w3.org/WoT/IG/ (proxy to the WoT IG blog 
> https://www.w3.org/blog/wotig/)

It should proxy to https://w3c.github.io/wot-marketing/ig/

Note: we decided keeping up with our own blog is too much work. We also said that IF we want to make a blog entry we can do it within the general W3C blog (https://www.w3.org/blog/) with a "WoT" label or so.


> https://www.w3.org/WoT/IG/track/ (legacy Tracker that was archived)

@ashimura confirmed that we don't use the W3C Tracker any more.

> https://www.w3.org/WoT/IG/wiki/Main_Page

The https://www.w3.org/WoT/IG/wiki/ space should exist further, we use it a lot!

> https://www.w3.org/WoT/IG/kaz/protocol-binding.png (and .svg)

@ashimura mentioned that we used the figure in the past. The concept is already included in the WoT Architecture spec and we don't need that figure any more.

> https://www.w3.org/WoT/WG/ (proxy to https://w3c.github.io/wotwg/)

It should proxy to https://w3c.github.io/wot-marketing/wg/

> https://www.w3.org/WoT/ws-2019/ (proxy to 
> https://w3c.github.io/wot/workshop/ws2/)

I think we can leave it as it is right now.
Content can be found here https://github.com/w3c/wot/tree/master/workshop/ws2

**Comment by sebastiankb** [comment]
we should add the link behind the video preview of the welcome page when the video is available on youtube or w3c

**Comment by sebastiankb** [comment]
In today's TD call we have to check the status of

- [ ] https://github.com/w3c/wot-marketing/pull/122
- [ ] https://github.com/w3c/wot-marketing/issues/123
- [ ] https://github.com/w3c/wot-marketing/issues/121
- [ ] https://github.com/w3c/wot-marketing/issues/84
- [ ] https://github.com/w3c/wot-marketing/pull/117

**Comment by koalie** [comment]
Hi all, since last week, the systems team performed successfully a few tests to validate the suggested redirection setup approach. I am happy to relay that we are ready on our side and to please confirm the date of when to do the switch.

**Comment by danielpeintner** [comment]
One final note. _Before_ we setup the redirection we need to change the following line
https://github.com/w3c/wot-marketing/blob/6e4d039a51fa5a0b62fab4ca717b0c44882304fc/docs/_config.yml#L5
to
`baseurl: "/WoT"`
since this will be the *new* baseurl (see https://www.w3.org/WoT/).

**Comment by ashimura** [comment]
I worked with the System Team and now:
  https://www.w3.org/WoT
and
  https://w3c.github.io/wot-marketing/
are identical using the redirection.

The other requirements are as follows:

* @draggett 's old contents to be kept as a historic record:
  * [x] https://www.w3.org/WoT/demos/rdf/
  * [x] https://www.w3.org/WoT/demos/shrl/
  * [x] https://www.w3.org/WoT/demos/td2ttl/
  * [x] https://www.w3.org/WoT/talks/2016-04-27.pdf

* IG page redirection:
  * [x] https://www.w3.org/WoT/IG/ => https://w3c.github.io/wot-marketing/ig/
  * [x] https://www.w3.org/WoT/ig/ => https://w3c.github.io/wot-marketing/ig/
  * [ ] need yet another redirection for https://www.w3.org/WoT/ig/ => https://w3c.github.io/wot-marketing/ig/ ?
  * [ ] how to handle https://www.w3.org/blog/wotig/ ? - OK to simply keep it as a historic record?

* IG Tracker:
  * [x] https://www.w3.org/WoT/IG/track/ removed

* Wiki pages:
  * [x] https://www.w3.org/WoT/IG/wiki/Main_Page kept as is

* Kaz's old images:
  * [x] https://www.w3.org/WoT/IG/kaz/protocol-binding.{png,svg} simply removed

* WG page redirection
  * [x] https://www.w3.org/WoT/WG/ => https://w3c.github.io/wot-marketing/wg/
  * [x] https://www.w3.org/WoT/wg/ => https://w3c.github.io/wot-marketing/wg/
  * [ ] need yet another redirection for https://www.w3.org/WoT/Wg/ => https://w3c.github.io/wot-marketing/wg/ ?
  * [ ] how to handle https://w3c.github.io/wotwg/ ? - kept as a historic record?

* 2nd workshop page:
  * [x] https://www.w3.org/WoT/ws-2019/ => https://w3c.github.io/wot/workshop/ws2/

Let's check the results at:
  https://www.w3.org/WoT
and
  https://w3c.github.io/wot-marketing/
to see if there are any remaining issues there.

**Comment by sebastiankb** [comment]
new webpage is launched
