### ISSUE TITLE
How to handle the WoT Japanese CG?

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-marketing#121]
Hello WoT Marketing Task Force,

I am submitting this issue for the possible description on the newly created [WoT Japanese CG](https://www.w3.org/community/wot-jp/) with following details.

**Problems:**

The [WoT welcome page](https://w3c.github.io/wot-marketing/) has a [subpage on the WoT CG](https://w3c.github.io/wot-marketing/cg/) but there is no description about the [newly created WoT Japanese CG](https://www.w3.org/community/wot-jp/). So we should add some description about the new CG too.

**Comment by sebastiankb** [comment]
A proposal would be that we have a drop-down selection for "Community Group**s**" (like for "Activities") which have the "W3C WoT – Community Group" and "WoT Japanese CG" . 

@ashimura may I ask you to provide a description for the new CG?

**Comment by danielpeintner** [comment]
An alternative would be sticking with the _one_ CG navigation but add content for both CGs to the page itself.

I think this is even simpler but either way is fine for me.

Once we know which way to go I can help with applying the changes...

**Comment by sebastiankb** [comment]
based on the discussion from last week it seems that the one CG navigation seems to be preferred option. @danielpeintner May I ask you to provide a PR for today's marketing call

**Comment by danielpeintner** [comment]
Note: @ashimura volunteered to work on a PR. I can help in case also...

**Comment by danielpeintner** [comment]
resolved by https://github.com/w3c/wot-marketing/pull/128
