### ISSUE TITLE
WoT Video page - Navigation

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#123]
We talked about creating a page that contains thumbnails for the WoT videos we have (and we will get in the future) and point where the according videos are hosted.

Do we have good idea how someone can navigate to this page on
https://w3c.github.io/wot-marketing/

I suggest to rename the navigation entry "Documentation" to "More" and we create 2 sub-navigation items
* Documentation
* Videos

Does that make sense?

**Comment by sebastiankb** [comment]
this is ok from my side

**Comment by danielpeintner** [comment]
see a first proposal in PR https://github.com/w3c/wot-marketing/pull/125

**Comment by danielpeintner** [comment]
more videos, see https://github.com/w3c/wot-marketing/pull/129

**Comment by sebastiankb** [comment]
issue solved based on current webpage version
