### ISSUE TITLE
Second W3C Workshop on the Web of Things misses report

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#124]
@mkovatsc _noticed_ that https://www.w3.org/WoT/ws-2019/ still does not have a report (grayed out)

**Comment by danielpeintner** [comment]
FYI: the content can be found here: https://github.com/w3c/wot/tree/master/workshop/ws2

Shall I provide a PR?

**Comment by egekorkan** [comment]
@ashimura mentioned that there is a report and that we should simply link to it.
