### ISSUE TITLE
Full size photos

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#13]
At the moment, the repository contains full-sized photos of everything. However, these are too big and are loaded like moving down a blind on a web page. I find it bad for the user experience. An example is this: https://www.w3.org/blog/wotig/2017/02/27/w3c-web-of-things-joint-igwg-meeting-in-santa-clara-5-9-february-2016/
(Make sure to do a force-refresh to see the page loading)
Even with a good Internet connection, this image takes 1-2 seconds to load and in TPAC Fukuoka it was taking more than 5 seconds to load. I think we should keep the full-size images but use 500kB (just a rough number) sized images in web pages. Some content management solutions do this automatically but we cannot rely on it since these photos can be used in other locations as well.

**Comment by egekorkan** [comment]
In the call of 31.10.2019 we have discussed that [this](https://www.w3.org/2019/09/wot-f2f/photos/0917/) can be used to get the different photo sizes. [Link to minutes](https://www.w3.org/2019/10/31-wot-marketing-minutes.html)

**Comment by danielpeintner** [comment]
@egekorkan still relevant?

**Comment by egekorkan** [comment]
I think we can close it but noting the following link somewhere is important I think. In the future, we can put the nice photos of plugfests on our website to give it a more human feeling :)

https://www.w3.org/2019/09/wot-f2f/photos/0917/
