### ISSUE TITLE
Transforming all wotig blog entries to the w3c main blog

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#142]
To keep all blog entries at https://www.w3.org/blog/wotig/ we should transform those to the w3c main blog w3.org/blog

@koalie will check who can do that transformation.

**Comment by koalie** [comment]
Hi @sebastiankb 
I will let you know as soon as I find out. Sorry I missed that ping.

**Comment by sebastiankb** [comment]
@koalie are there some news here?

**Comment by koalie** [comment]
> @koalie are there some news here?

No, but I will ask again internally.
(I expect to find out/let you know around early June.)

**Comment by sebastiankb** [comment]
from today's marketing call: It would be a good idea to redirect the old IG blog page to the new WoT page.

**Comment by sebastiankb** [comment]
@koalie are there some news here?

**Comment by koalie** [comment]
Hello @sebastiankb 

Done! Redirects are put in place.

 OLD URI: https://www.w3.org/blog/wotig
 NEW URI: https://www.w3.org/blog/group/ig-wot/
