### ISSUE TITLE
Press Release - Cleanup

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#145]
We have several links pointing to a previous press release
* on README pointing to a draft version, see https://github.com/w3c/wot-marketing#press-releases
* in docs folder pointing to final destination, see https://github.com/w3c/wot-marketing/blob/master/docs/pressrelease-wot-rec.html

Shall we clean-up those links/files: I suggest doing the following
* on README pointing to final destination, see https://www.w3.org/2020/04/pressrelease-wot-rec.html.en
* remove the pressrelease-wot-rec.html file in docs folder

Any opinion?

**Comment by egekorkan** [comment]
We will clean this up, discussion should continue at #291
