### ISSUE TITLE
Jekyll Preview PRs

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#148]
We should look into possibilities to preview PRs affecting the website.

At the moment we can just use GitHub diffs but do not see the actual *rendered* result/website.

**Comment by danielpeintner** [comment]
Note: I have troubles finding a good way of previewing Jekyll PRs other than locally.

There are commercial offers like  [render](https://render.com/docs/deploy-jekyll) but I guess this is not what we are looking for.

Does W3C have some kind of tooling since it offers also preview for specs, see for example https://github.com/w3c/wot-thing-description/pull/1058
@ashimura @dontcallmedom  do you know?

**Comment by dontcallmedom** [comment]
I believe the WAI Team has been using netlify for that purpose - I don't know if @SteveALee can share pointers to their setup; as far as I know, W3C as a whole doesn't have a supported system for this at this time.

**Comment by SteveALee** [comment]
Indeed WAI does use the excellent Netlify GitHub integration. It even works with our complex site config using git submodules with some extra care. 

Basically whenever a PR or branch commit is made Netlify gives a preview build and deploy. It shows info right in the PR on GitHub too. For example (at random) see the "All Checks passed" section in this [PR](https://github.com/w3c/wai-accessibility-principles/pull/36). Click on "details" to go to the preview.

Netlify is an excellent platform with many features but we just use preview deploys at the moment. This [post](https://www.netlify.com/blog/2021/02/23/terminology-explained-atomic-and-immutable-deploys/) explains two key features.

We are also using GitHub actions to a) build and publish the WAI site to github pages where it gets proxied into the w3c site b) transfer files between repos.

Happy to chat more about it and help you explore. @slhenry can give you more of a "users" perspective.

**Comment by SteveALee** [comment]
@danielpeintner see [this preview](https://wai-website-theme.netlify.app/overview/) for details of how it all works.

**Comment by danielpeintner** [comment]
Thank you very much @SteveALee and @dontcallmedom !
This looks VERY promising. I need to talk to @ashimura whether he can setup the process since I do not have admin rights.

Once again I would like to say thank you for your help!

**Comment by egekorkan** [comment]
Options:
- WoT Japanese CG is using Netlify. @egekorkan can contact @k-toumura . The downside is that render or netlify are tied to private accounts. So changing any setting about the rendering can be done only by one person
- GitHub actions already run this rendering: https://github.com/w3c/wot-marketing/actions/runs/1745310698 @egekorkan will investigate to see if it is possible to see the rendered versions

**Comment by SteveALee** [comment]
> The downside is that render or netlify are tied to private accounts. So changing any setting about the rendering can be done only by one person

Not for Netlify:

* You have teams and can assign multiple people to the team
*  We use the github integration for CI/CD when anyone pushes to a branch or a PR (configurable)

Happy to chat through the options

**Comment by danielpeintner** [comment]
Note: yesterday we "discovered" that allowing multiple accounts (team members) for Netlify might cost money.

If we look at it pragmatically, it doesn't matter. If in the future the current person is no longer available, someone else can set up the same thing again. We just need to adapt the GitHub actions and we are fine again. Or am I missing something here?

**Comment by SteveALee** [comment]
So the WAI have a W3C_Team "unlimited open source" account and @shawna-slh originally intended that others in the w3c could use this. That way the previews will NOT depend on individuals and can be easily managed.

I suggest you ping Shawn, or the three of us can arrange a chat to guide you through using Netlify previews.

**Comment by egekorkan** [comment]
That sounds promising, thank you @SteveALee . @shawna-slh , if that is indeed correct, I would like to set up a small meeting with you :)

**Comment by egekorkan** [comment]
Call of 01.03: In the worst case, @egekorkan will tie the netlify account to his GitHub account and archive the small build command in this repo so that others in the future can open their own account and render previews

**Comment by egekorkan** [comment]
I have setup a personal netlify website with this page being rendered at https://wot-marketing.netlify.app/

**Comment by egekorkan** [comment]
See also https://github.com/w3c/wot-marketing/pull/279

**Comment by egekorkan** [comment]
@egekorkan I will document this in the README so that others can do this as well
