### ISSUE TITLE
Daylight Saving changes to be applied to the teleconf time table

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-marketing#155]
Due the Daylight Saving Time in US and Europe, we need to update the teleconf timetable:
  https://www.w3.org/WoT/activities/general/

as follows:
1. for the period between 15 March 2021 and 26 March 2021:
    * In US, all the times don't change
    * In Europe and other countries, all the calls start one hour earlier
    * See the [timetable on the WoT wiki](https://www.w3.org/WoT/IG/wiki/Main_Page#WebConf_Meetings)
2. for the period on and after 29 March 2021:
    * In US, all the times don't change
    * In Europe, the starting time goes back to the usual time (=one hour later again)
    * In other countries, the starting time remains one hour earlier
    * I'll update the [timetable on the WoT wiki](https://www.w3.org/WoT/IG/wiki/Main_Page#WebConf_Meetings) during the weekend of 27-28 March 2021 accordingly

**Comment by danielpeintner** [comment]
I agree and we should update the timetable.

I wonder whether we should _directly_ jump to "2." since all regular meetings the next 2 weeks are cancelled, see https://www.w3.org/WoT/IG/wiki/Main_WoT_WebConf#Cancellations

Any opinion?

Note: I can provide a PR...

**Comment by ashimura** [comment]
fixed by PR #157
