### ISSUE TITLE
Websites are difficult to manage

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#16]
Hello WoT Marketing Task Force,

I am submitting this issue for a **feature request** with following details.

**Problems:**

* The [IG](https://www.w3.org/WoT/IG/), CG and [WG](https://www.w3.org/WoT/WG/) website are created using different technologies such as WordPress, GitHub etc.
* How the website are managed and generated are not transparent to the outside, making it harder to contribute.
* WordPress restricts the contribution to a certain set of users and makes it **impossible** for others to contribute directly.
* WordPress makes it more difficult to set up version control.

**Requirements:**

* Constrict all websites to the same technology
* Make the website source code open source and thus visible for everyone.
* Make it clear where the source code is stored and managed
* Make it possible for anyone to request a change to the website but allow a set of people to accept it
* Have version control, like git.

**Solution Proposals:**

* Move [every website](https://danielpeintner.github.io/wot-pages/) to GitHub as a [public repository](https://github.com/danielpeintner/wot-pages/tree/gh-pages) where WoT members have write access. This solves the requirements in the following way:
  * The code will be open source, thus visible for everyone
  * The source code will be managed by GitHub which is familiar to everyone in the WoT group since all the standardization development goes on GitHub
  * Anyone can contribute to the public repository by making Pull Requests. These Pull Requests can be then merged by anyone with a write access, ideally after talking in the task force meeting.
  * GitHub is based on git version control system that stores all the previous versions and allows for multiple branches to exist

**Background information:**

This issue has been created since WG, IG and CG are not maintained properly due to the problems mentioned above. As spoken in the TPAC 2019 in the working group meetings, we need to market our work better and websites are one of the primary ways to do so.

**Comment by danielpeintner** [comment]
Can be closed? @egekorkan ?

**Comment by egekorkan** [comment]
Yes! :)
