### ISSUE TITLE
API Specification Conference 2021

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#163]
After a succesful event last year (also an issue at #66), the API Specifcations Conference has a new edition this year (https://events.linuxfoundation.org/openapi-asc/). I think it would be again worthwhile to present WoT there. However, I would say that a new presentation and type of information would be better, i.e. not saying again that we have a spec to describe APIs for IoT devices. See last year's talk at https://www.youtube.com/watch?v=ySLuAIoz0Dg&list=PLcx_iGeB-Nxil4S7-0Y1Y5r0oLahy3f0Y&index=13

Some suggestions on how to make a different talk this time:

1. Same content but approach it differently, major change for the start but similar ending, i.e. technical part stays the same but starting with something like "what if we wanted to do APIs for IoT devices, how would it look? -> Then give many examples and point out interoperability problem"
2. Assume that the audience knows TD 1.0, explain new stuff : Could be too technical and boring. 
3. Talk about Discovery: I think this would be again too technical and for people to be excited about it, they have to be excited about TD in the first place. Otherwise, the TDD is just a database.
4. Talk about Scripting: This could be quite interesting since I am not aware of other talks that do a similar presentation, i.e. using API specifications to enable easy scripting. It would be interesting for us to get some feedback as well.

I think we should decide on something together in a marketing call.

**Comment by egekorkan** [comment]
Call for submissions is already open, deadline is June 11

**Comment by sebastiankb** [comment]
from today's marketing call:
- @sebastiankb will check with Pedram if we submit a similar presentation as for the [IIoT conference](https://www.iiot-conference.de/index.php?source=0)
- fallback would be a more generic presentation about WoT such as about WoT use cases

**Comment by sebastiankb** [comment]
from today's marketing call: @ege will provide an abstract which we can discuss the next time

**Comment by egekorkan** [comment]
Below is my abstract proposal that follows the discussions in the calls and also the CFP of the conference at https://events.linuxfoundation.org/openapi-asc/program/cfp/#overview

# API Specifications Conference CfS

Proposal: Talk
Speaker: Ege Korkan

## Session description

As a member of the W3C Web of Things Working Group, I will be talking about the recent work of the working group and I will do a hands-on demonstration in a smart home use case and industrial automation. This will be building upon my last year's talk (https://sched.co/deol).

After the publication of the Thing Description (TD) Recommendation, the working group has been developing ways to discover TDs through the [Discovery API](https://www.w3.org/TR/wot-discovery/) and also bring modeling mechanisms inspired by object-oriented programming to have reusable TD snippets (https://www.w3.org/TR/wot-thing-description11/#thing-model).

TDs allow developers to write API Consumers in different application domains and in a protocol-abstracted fashion. I will demonstrate this with a live-coding session and writing code snippets that look very similar but are able to work in a smart home environment and in industrial automation, showcasing how the concepts of the Web can be used in a variety of domains.
 
## Notes to organizer

Note1: The two specification documents linked above will have an almost final stage at the time of the conference.

Note2: The outline will be as follows:

- Recap on the Thing Description and the Web of Things.
- Thing Model mechanism
- TD Discovery
- Live-coding with 2 use cases

**Comment by mmccool** [comment]
Thoughts from main call:
- Mention Thing Model by name in abstract
- Say "WoT Discovery process" - the directory API is just part of it

**Comment by egekorkan** [comment]
I have submitted the talk. There is still time to edit. Please find the attached pdf-printed of the session and speaker description:
[Thing Models, Discovery and mo... - API Specifications Conference ... - My Events - Speaker profile @ Sessionize.com.pdf](https://github.com/w3c/wot-marketing/files/6601616/Thing.Models.Discovery.and.mo.-.API.Specifications.Conference.-.My.Events.-.Speaker.profile.%40.Sessionize.com.pdf)

**Comment by egekorkan** [comment]
Sadly my submission didn't get accepted. Closing
