### ISSUE TITLE
No Web of Things social media presence exists

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#17]
Hello WoT Marketing Task Force,

I am submitting this issue for a **feature request** with following details.

**Problems:**

* There is currently no social media presence of any WoT group, which reduces our reachable audience.
* W3C Twitter account published only publication related information.
* There is no official way to give a heads-up to the WoT developers about changes. It shouldn't be mandatory to subscribe to the email lists or poll the blog posts for new information.

**Requirements:**

* Having active social media accounts such as Twitter.
* Have a way to inform developers on small new features without polluting blog posts section.

**Solution Proposals:**

* Set up a main Twitter account that can be used by CG, IG and WG. An example of the CSS WG is [here](https://twitter.com/csswg)

**Background information:**

W3C has a [Twitter account](https://twitter.com/w3c) where news about publications are published. However, we need a more granular approach that can publish information on little but important things for WoT developers. When we decide to add a feature to the TD spec, it would be nice to give a heads-up to the developers. E.g. "Today we have decided to introduce the keyword multipleOf to the DataSchema vocabulary of Thing Description. Check out the discussion here (link to GitHub issue)". This could be also done by individual people, like [some CSS group members do](https://twitter.com/bdc/status/1100921258839953408).

My observation is that the Web community is the most active on Twitter.

**Comment by egekorkan** [comment]
We have agreed on the call of 14.11.2019 that we will discuss with the W3C Marketing and Communications team and then with the @w3c/csswg in order to establish a Twitter account.

**Comment by koalie** [comment]
I'm happy to help set that up for you.

**Comment by egekorkan** [comment]
Thank you @koalie ! Is there a naming convention for the Twitter account?

**Comment by koalie** [comment]
> Thank you @koalie ! Is there a naming convention for the Twitter account?

Yes, we recommend prepending "W3C_".
We also recommend following accessibility advice to use camelcase (each word begins with a capital letter, no intervening spaces or punctuation).

**Comment by dauwhe** [comment]
> We have agreed on the call of 14.11.2019 that we will discuss with the W3C Marketing and Communications team and then with the @w3c/csswg in order to establish a Twitter account.

I think mentioning the CSSWG in that fashion is resulting in 75 people getting notifications about this thread. Would editing the comment help?

**Comment by sebastiankb** [comment]
in today's web meeting call we made the following resolution:

>resolution: to ask that a twitter account with the name W3C_WoT be created, with at minimum WoT WG chairs and editors given the rights to post

**Comment by koalie** [comment]
> in today's web meeting call we made the following resolution:
> 
> > resolution: to ask that a twitter account with the name W3C_WoT be created, with at minimum WoT WG chairs and editors given the rights to post

https://twitter.com/W3C_WoT

I'll follow-up with setup information.

**Comment by danielpeintner** [comment]
Twitter account was setup and is live, see https://twitter.com/W3C_WoT

@egekorkan shall we close the issue or do we plan to create yet another account? I don't think so...
