### ISSUE TITLE
WoT Implementations

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#176]
As mentioned in the marketing call we did [ask](https://lists.w3.org/Archives/Public/public-wot-ig/2016Jun/0011.html) a long time ago for WoT implementations which got collected here: 

https://www.w3.org/WoT/IG/wiki/Implementations 

I guess we should try to
* ask for *fresh* feedback and check the conformance (difficult)
* move the content to the website

**Comment by mmccool** [comment]
We are still missing a bunch:
- SayWoT - Siemens
- WebThings 
- ECHONET (partially compliant)
      - they themselves do not do compatible implementations, but member companies may
- Compatible commercial implementations - need to check with Bosch.io, Schaeffler, Fujitsu, etc.

We need to discuss 
- how to deal with "partial" implementations; how compliant does something have to be to be included?
- how to distinguish between formal implementations used for REC transition vs. just "compatible implementations" that we can put on the web site
- is putting an implementation on the web site "promising" anything?  Do we need a disclaimer? 
- should we distinguish commercial and experimental implementations
- how in general do we do compliance testing?

**Comment by lmy441900** [comment]
Searching for `web-of-things` / `webofthings` / `wot` tags on GitHub / GitLab can also give us a view on WoT-related projects.

It looks like https://www.w3.org/WoT/IG/wiki/Implementations now contains some abandonware; there's even rot link (e.g. ub.js). Some projects haven't been developed for years, so I don't think they could follow the standard. There are projects that claim to be compliant with WoT, but it's not obvious and difficult to evaluate (mostly "just compatible implementations").

I think the implementation list can be merged with https://www.w3.org/WoT/developers/ . There can be classifications, e.g. IG-endorsed, commercial, experimental. You may proactively search for projects or accept submissions. There should definitely be a _stddisclaim.h_. This can also be seen as a portal to newcomers, as (from my perpective) most often people just want to use the technology, but they usually first go to the WoT homepage.

**Comment by sebastiankb** [comment]
from today's marketing call:
- group decides to have open source and commercial implementations in the https://www.w3.org/WoT/developers/ 
- each implementation should make clear that they are open source or have a commercial license 
- we should close https://www.w3.org/WoT/IG/wiki/Implementations  and do a backup before as record. https://www.w3.org/WoT/developers/  should be the single place with latest implementations (@lmy441900 many thanks for the pointer)
- @danielpeintner will take care

**Comment by danielpeintner** [comment]
>     * we should close https://www.w3.org/WoT/IG/wiki/Implementations  and do a backup before as record. https://www.w3.org/WoT/developers/  should be the single place with latest implementations (@lmy441900 many thanks for the pointer)

The content is to be moved to the archive, see https://github.com/w3c/wot-marketing/pull/187

The `old` [wiki page](https://www.w3.org/WoT/IG/wiki/Implementations) points to the developer section now.

**Comment by egekorkan** [comment]
The content is now at https://www.w3.org/WoT/developers/

Closing as part of the call of 09.11.2021
