### ISSUE TITLE
Where to place videos?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#178]
We need a good place where we can store videos like from recodred presentation. Github has some limitations regarding big files. 

@koalie we like to ask you if there is a good place where we can archive and share videos.

**Comment by ashimura** [comment]
@koalie our point is "possible easier/simpler solution" than asking @dontcallmedom every time :)

**Comment by dontcallmedom** [comment]
if YouTube is sufficient for your needs, I can work with @ashimura on giving him access to upload videos there

For our StreamFizz platform, we're waiting for them to provide us the entry points that would make this possible - for the moment, @swickr or I are in the critical path I'm afraid

**Comment by danielpeintner** [comment]
@ashimura to talk with @dontcallmedom for the credentials (YouTube and StreamFizz)

**Comment by egekorkan** [comment]
Marketing Call 16.11.2021. @ashimura to talk with Dom

**Comment by egekorkan** [comment]
Given that we are not planning to put anything new for now and that YouTube is fine, I will simply close this issue. Please reopen if needed
