### ISSUE TITLE
Process/Tooling to Keep WoT Events Up to Date

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#179]
see:
* https://www.w3.org/WoT/IG/wiki/Main_WoT_WebConf#Events
* https://www.w3.org/WoT/activities/general/ (resolved by https://github.com/w3c/wot-marketing/pull/180, still proper links missing)

**Comment by danielpeintner** [comment]
resolved by now

**Comment by sebastiankb** [comment]
from today's marketing call:
- we can evaluate to use an existing W3C organization tool like [here](https://www.w3.org/blog/talks/event/w3c-wai-interactive-update-guidelines-emerging-technologies-and-new-resources/)  or [here](https://www.w3.org/participate/eventscal.html) 
- @ashimura will check with W3C team if we can use this

**Comment by mmccool** [comment]
is this resolved?  I think we should close this and have different (dated) issues for each update.  See https://github.com/w3c/wot-marketing/issues/196
On the other hand, if this issue is about tooling to automatically update events, perhaps we can update the title to something like "How to Keep WoT Events up to Date"

**Comment by mmccool** [comment]
Updated title, let's use this issue to talk about the process and tooling as opposed to specific manual updates.

**Comment by sebastiankb** [comment]
we should check the email from @plehegar about the calendar usage [here](https://www.w3.org/Guide/meetings/organize.html#calendar) (member only).

**Comment by FadySalama** [comment]
From today's call:

- It's very hard to find the actual times for meetings (where is the source of truth?)
- Adding import capability for W3C WoT calendar for new people to join
- We need analysis to see the need for people to find our meetings (W3C members know where to look, do others do as well?)
- Next step: make it easier for people to find events

**Comment by egekorkan** [comment]
Call of 19.04:
- this issue is settled now, the official W3C calendar is being tracked at #268 . Closing
