### ISSUE TITLE
History of the standardization is unknown

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#18]
Hello WoT Marketing Task Force,

I am submitting this issue for a **feature request** with following details.

**Problems:**

* There is no clear and concrete information on the standardization's history, which makes it time-consuming to prepare such information to present to newcomers.
* History is understandable only through blog posts in the IG website.

**Requirements:**

* A chronological history of the WoT Standardization activity in W3C.
* A list of important events in the WoT Standardization activity in W3C.

**Solution Proposals:**

* A markdown file that can read on GitHub or desktop that lists the events in a chronological order. Important events would be then marked with bold or a special symbol.
* This can be then copied into presentations, Wikipedia, our wiki.

**Background information:**

This issue has been created when the work on Wikipedia has started. There it was realized that it is difficult to convey how everything has all started. In the meantime, I consider it powerful when we can show how much work has been put into W3C WoT by giving a timeline.

**Comment by egekorkan** [comment]
We have agreed during the call of 14.11.2019 that @takuki and @egekorkan will work on this issue to generate the history.

**Comment by takuki** [comment]
I started to draft a history of WoT Standardization.
It is work in progress. Please see [here](https://www.w3.org/WoT/IG/wiki/2020/01/Marketing_WoT_Standardization_History).

**Comment by egekorkan** [comment]
Also Figure 1 at https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9765991 is quite helpful
