### ISSUE TITLE
Logo links are broken

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#184]
I am not sure what really caused this but the logos that are visible at https://www.w3.org/WoT/IG/wiki/Web_of_Things_Logos are not retrievable, i.e. https://www.w3.org/WoT/IG/wiki/File:WOT-transparent.png returns a 503 error.

**Comment by danielpeintner** [comment]
In my case everything works as expected. Both links work...

**Comment by relu91** [comment]
It works also from my side.

**Comment by egekorkan** [comment]
Now they do for me too, probably got caught in an update phase. Closing
