### ISSUE TITLE
Adding Social Media Icons on WoT Pages

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#188]
In order to increase our exposure, it would be nice to use icons from [shields.io](https://shields.io/) to link our social media pages from our GitHub repositories. Currently, we have only Twitter but there were discussions on having a YouTube channel as well. Below is an example for Twitter : 

[![Follow on Twitter](https://img.shields.io/twitter/follow/W3C_WoT.svg?label=follow+W3C_WoT)](https://twitter.com/W3C_WoT)

This would like the following for the TD repository:

![image](https://user-images.githubusercontent.com/20195407/125701582-58c67ab0-3571-4239-a4f0-1e5a85dfef55.png)

**Comment by egekorkan** [comment]
We have more than 15 unique visitors per day (most days) just to the TD GitHub repository, so why not :) Screenshot below is from the traffic tab of the insights tab of the TD spec:
![image](https://user-images.githubusercontent.com/20195407/125701723-cb703151-8744-40bd-a0ed-6ba478629a34.png)

**Comment by egekorkan** [comment]
Also StackOverflow badge would be nice

<img alt="Stack Exchange questions" src="https://img.shields.io/stackexchange/stackoverflow/t/web-of-things?style=plastic">

Couldn´t manage to do it for some reason though...

**Comment by danielpeintner** [comment]
Marketing Call 2021-07-20
* @mmccool  mentions we should link back to website
* a *general* and consistent header across all our repositories 

@egekorkan @mmccool  can you provide a proposal?

check with @koalie whether this ok (privacy?)

**Comment by koalie** [comment]
Hello @danielpeintner 
I don't see anything that goes against the [W3C privacy statement](https://www.w3.org/Consortium/Legal/privacy-statement-20140324).

**Comment by danielpeintner** [comment]
> I don't see anything that goes against the [W3C privacy statement](https://www.w3.org/Consortium/Legal/privacy-statement-20140324).

Great! There were some concerns raised during the marketing call...

**Comment by egekorkan** [comment]
Linking back to the website is not the goal here. That should be done on top of this.

**Comment by danielpeintner** [comment]
Note: @egekorkan provided a PR in the TD repository, see https://github.com/w3c/wot-thing-description/pull/1196

**Comment by egekorkan** [comment]
This is now implemented everywhere. Propose closing

**Comment by danielpeintner** [comment]
related but different issue, see https://github.com/w3c/wot-marketing/issues/190

Hence, closing seems fine.
