### ISSUE TITLE
Websites are using different designs

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#19]
Hello WoT Marketing Task Force,

I am submitting this issue for a **feature request** with following details.

**Problems:**

* The [IG](https://www.w3.org/WoT/IG/), CG and [WG](https://www.w3.org/WoT/WG/) website are looking different from a visual and navigation point of view. This renders the W3C WoT unprofessional. 
* It is difficult to navigate between these websites.
* Some content that can be written for the 3 websites (like announcing a workshop) has to be re-written for each website with its style of formatting.

**Requirements:**

* Constrict all websites to the same design language.
* Make the content independent from each website but usable in each website by simple referencing.
* Streamline navigation between the websites through a unified header/menu bar. 

**Solution Proposals:**

* Use the same design template for each website. An example proposal can be found [here](https://w3c.github.io/wot-marketing/) which is built with Jekyll. The style itself is not a proposal but the fact of using the design is.

**Background information:**

This issue has been created since WG, IG and CG websites look completely different and makes it difficult to present them in events, such as conferences, meetings etc.

**Comment by danielpeintner** [comment]
As discussed during last call I would like to propose an email repsonse to Coralie w.r.t. the following news 
https://www.w3.org/2019/11/website-redesign-rfp.html

Proposal: 

> Hi Coralie,
>
> I support the initiative to redesign the W3C website. A *fresher* design can only bring advantages besides the technical improvements.
> 
> However, I was wondering whether this redesign initiative also includes the websites used by working groups, interest groups and community groups?
> 
> The reason why I am asking is that we (as the WoT group) are currently facing a dilemma with these different group pages. All these pages are using a different technology (WordPress, Github, …) and look *visually* different. Hence, the WoT group is aiming for *one* visual appearance across all our pages to give interested people from the outside a consistent view.
> 
> Thanks for any insight.

Please comment if you have concerns.

**Comment by egekorkan** [comment]
In the call of 14.11.2019 we have reached the resolution to bring this to the main call of 20.11.2019 for @sebastiankb to send this email (with the mention that IG and WG want this ) to the W3C Marketing and Communications team (Coralie) after the whole group's approval.

**Comment by sebastiankb** [comment]
The email looks good.  There seems to be no objection. I will send the proposed email to Coralie tomorrow.

**Comment by danielpeintner** [comment]
Can be closed? @egekorkan ?

**Comment by egekorkan** [comment]
Yissss
