### ISSUE TITLE
[website] Not easy to find contact information

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#192]
When I am on the https://www.w3.org/WoT/ , there is no easy way (outside of Twitter) to contact us. It would be nice to have a contact tab or field somewhere that says something like:

- Technical Questions? -> Ask a question at Stackoverflow
- Participation to the groups -> Send an email to the chairs
- Errors or unclear parts of a specification -> Create an issue on GitHub. 
- (Whatever comes out of https://github.com/w3c/wot-marketing/issues/146)

**Comment by danielpeintner** [comment]
I suggest to have a new navigation entry under "More" -> "Contact & FAQ" that points to a *new* page with the information provided by @egekorkan.
Moreover, a "Contact" links should/could be also shown in the footer of the website...

**Comment by mmccool** [comment]
- I agree better contact info would be useful
- I note the badges that are in the READMEs now are not on the web page
- A separate "contacts" page makes sense (and a link at the bottom of the page or in the footer to it)
- Emails can be to chairs and/or staff, but we have to be careful to avoid robots scraping them (e.g. formatting them as images, etc)
- Could set up discord server (provides indirect access to emails, but public)
- Github issues are also reasonable means of contact and should be mentioned (use "wot" as the main channel; but is public)
- ... and now there is the issue of too many ways to contact us; what is the *primary* means of contact?
- public channel can use "w3c/wot" github issues; how to handle private communications (without posting emails directly)?

**Comment by egekorkan** [comment]
Some answers to the comments above:

- > I note the badges that are in the READMEs now are not on the web page

I think it is possible to use shields.io for this as well.

- > Could set up discord server (provides indirect access to emails, but public)

Discussion should be made at #146 

- > Github issues are also reasonable means of contact and should be mentioned (use "wot" as the main channel; but is public)

I disagree with this. The word issue is offputting, especially for newcomers to GitHub. They think that should be used for bug reports etc. but not for questions or discussions. JSON Schema Slack channel is very active compared to their issues.

**Comment by sebastiankb** [comment]
from today's marketing call:
- there was the discussion if we should enable the "discussion" feature of github
- this area can be provided to newcomers to provide questions
- group agrees (if we want to have "discussion") to have it only available at a single place like w3c/wot repo
- have to discuss this in the main call

**Comment by FadySalama** [comment]
from today's call:

- we have less control over stackoverflow -> much better control in github
- can google index github discussion? -> stackoverflow allows this
- use both: questions in stackoverflow, discussions and opinions on github
- we need to explain this on the webpage!

**Comment by egekorkan** [comment]
Closing and moving discussion to #234
