### ISSUE TITLE
Adding simple WoT introduction video (and reorganize video ordering)

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#194]
Some time ago I had done the video below. It is definitely less professional but recently some non WoT related people said that they actually liked it. So maybe some place after the professional video in our videos page?
https://youtu.be/lt_P2BU8e3I

**Comment by danielpeintner** [comment]
I think it perfectly matches with the also *practical* video from @relu91  on https://www.w3.org/WoT/videos/ 

Maybe we want to create a certain structure on the [videos](https://www.w3.org/WoT/videos/) page to group videos accordingly.

**Comment by egekorkan** [comment]
Yes, I think a structure would be adequate. The most recent one as THE official wot video. Then, different columns (in 16:9 screens) for "WoT in Events", "Explanatory Videos by Members" or similar :)

**Comment by mmccool** [comment]
I think we need both categorization (esp into "Starting Points" and "Contributions") and (reverse) chronological ordering.  Right now there are some older videos near the top of the list that are not really the best place to start.  If we do strict chronological ordering, the "starter" videos will get buried.

**Comment by sebastiankb** [comment]
from today's marketing call:
- we decided to create two new categories: "Tutorials" and "Interviews, Meetings, Conferences"
- the videos in the categories should be ordered by the dates (latest first)
- @danielpeintner will provide a proposal
- we should also think about the place where we will place the future tutorial videos from @egekorkan and @FadySalama. One idea is to have a link at the developer space or create a new section about tutorials
