### ISSUE TITLE
Web Page updates - August 2021

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-marketing#196]
Web page review, following updates needed:
- Remove cancellation box on event page
- Link to F2F wiki page (in addition to TPAC), mention testfest separately
```
- [TPAC 2021](https://www.w3.org/WoT/IG/wiki/F2F_meeting,_October_2021):
    - Plugfest Sept 28-Oct 2
    - vF2F Oct 5, 7, 20, 21, 22
    - Joint meetings week of Oct 14
```
Add following events (in reverse chronological order)
- DIoT Nov 8-12: https://oeg-upm.github.io/DIoT/
- IoT Tech Expo Sept 29: https://www.iottechexpo.com/northamerica/track/iot-digital-infrastructures-day-1/
- RIoT Sept 9-10: https://summit.riot-os.org/2021/

**Comment by mmccool** [comment]
Daniel will merge (and publish) the updates immediately.  The vF2F wiki page needs some cleanup, which we will do this week, and then we should probably publish a tweet mentioning the F2F and the other events noted.

**Comment by danielpeintner** [comment]
Note: the web page related parts should be resolved by https://github.com/w3c/wot-marketing/pull/197, see https://www.w3.org/WoT/activities/general/

**Comment by mmccool** [comment]
Looks like everything is done, closing.

**Comment by danielpeintner** [comment]
> The vF2F wiki page needs some cleanup, which we will do this week, and then we should probably publish a tweet mentioning the F2F and the other events noted.

I think the afore mentioned points are not done yet..

**Comment by sebastiankb** [comment]
from today's marketing call we close this issue. I will ping @egekorkan about the tweet
