### ISSUE TITLE
Interest Group page - short term

### ISSUE THREAD

**Issue by draggett** [w3c/wot-marketing#2]
The IG page is currently generated by WordPress and offers limited opportunities for us to customise it. 
* https://www.w3.org/WoT/IG/

For instance, I don't know how to change the colour of the red text at the top, nor how to change the HOME button to the /WoT/ landing page. I updated the content of the red text to be the same as for the IG on the landing page.

We now need new blog posts for the Munich workshop and the TPAC F2F. Any volunteers?

**Comment by danielpeintner** [comment]
The IG page (at least at the moment) is mainly about posts, news and events which are out-dated.

I guess we might want at least 2 new posts about
* the last F2F in Fukuoka
* the CR publication of the TD in May

The section about "Recent Presentations" is also very much out-dated. Personally I would remove things if we do not have the resources to update them.

Hope this helps

**Comment by egekorkan** [comment]
@draggett will be putting [the content](https://github.com/w3c/wot-marketing/blob/master/posts/draft/2019-10-tpac-update.md) generated by @mmccool on top of the page as the most recent news article.

**Comment by danielpeintner** [comment]
Since the new website is due to go online shortly, short term points are no longer relevant.

@draggett please reopen if you think differently
