### ISSUE TITLE
Twitter Background Image

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#206]
Currently, our Twitter profile has no background image, resulting in a big empty place on our Twitter profile (https://twitter.com/W3C_WoT). It would be nice if it is simply not empty. I have thought of using a frame from the official WoT video like the following:
![image](https://user-images.githubusercontent.com/20195407/137600631-e62cbf87-1e8b-4907-aa29-de4237d79e9f.png)
However, I am not entirely satisfied. Any other ideas?

**Comment by egekorkan** [comment]
Here are how the different options look like:
- Storyboard 24A: Sadly it is not a wide image, so it doesn't fit perfectly:
![image](https://user-images.githubusercontent.com/20195407/137902832-085407bb-40ec-429a-8d39-8e4a05ced150.png)
----
- Option 1 above: (ever worse fit)
![image](https://user-images.githubusercontent.com/20195407/137903096-353902b1-6d95-410f-9d33-1054722ebd35.png)
----
- Option 2 above:
![image](https://user-images.githubusercontent.com/20195407/137903236-2c00a432-99a2-4345-9680-b2129512334f.png)

----

In the end, I like option 2 the best

**Comment by relu91** [comment]
Personally, I like [W3C background](https://twitter.com/w3c) with a group photo. It gives a sense of community. We have some [group photos](https://www.w3.org/WoT/ws-2019/minutes.html) from Munich f2f. Other than this I would also vote for option 2.

**Comment by egekorkan** [comment]
Let's vote one final time:
1. @Citrullin last photo. @mmccool also liked it. React with :rocket: to vote for this
![image](https://user-images.githubusercontent.com/20195407/139840247-b6af0c09-bd52-4c1c-abc2-94dc14870842.png)

2. Group photo proposed by @relu91 . Comment from @mmccool : This will look like random people to outsiders. React with :heart: for this
![image](https://user-images.githubusercontent.com/20195407/139840359-9dca81c9-8a31-44e1-930b-ff720c2bf5d8.png)

3. Option 1 from above. React with :smile: for this one
![image](https://user-images.githubusercontent.com/20195407/139840519-d5c42bc7-403e-49fe-936a-eaa87d6d4d7d.png)

**Comment by egekorkan** [comment]
Call of 09.11.2021:
- We have decide to take option 1 (with :rocket:)

**Comment by egekorkan** [comment]
Closing since https://twitter.com/W3C_WoT now has the contribution of @Citrullin .

Thank you @Citrullin !

**Comment by danielpeintner** [comment]
Issue can be closed, right?

**Comment by egekorkan** [comment]
I thought I did, sorry :)
