### ISSUE TITLE
Activities tab is misleading

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#216]
Activities sound like events we have.

Proposal: Moving Activities under groups (or their respective group pages)
We should consider introducing `Events` and use it for documenting public events we have

**Comment by mmccool** [comment]
Thoughts: menu is quite long and mixes up task forces and "events".  Suggest the menu has only three entries: Task Forces, Events, and Meetings.  Then we break up the "General" page into three separate page that each of these points to.  Then to look at Task Forces, you would go to that page first, then the relevant TF.  more clicks, but a less confusing menu on the Activities tab.

Then Events is for one-off events, "Meetings" is for recurring meetings.

**Comment by egekorkan** [comment]
Call of 19.04: We seem to have forgotten to close it, closing now.
