### ISSUE TITLE
Should Marketing TF be in the Community Group

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#219]
As mentioned in some F2F meetings and main calls, maybe the marketing TF is better suited for a Community Group. Please express your opinions below.

**Comment by egekorkan** [comment]
Implications:
- No requirement for a charter if we are in a CG and if we do create a charter, it does not need review from the AC reps
- Anyone with a W3C account and not with membership can join

**Comment by danielpeintner** [comment]
I am still wondering to which WoT group the marketing task force belongs.

**Comment by egekorkan** [comment]
I have quickly checked the japanese CG and they have different TFs:
https://github.com/w3c/wot-jp-cg/tree/main/TF

Assuming that the work can be moved to the WoT CG (if _they_ would accept it), we would need to think if we want to have different TFs or have a marketing TF inside the WoT CG.

**Comment by relu91** [comment]
If we move to WoT CG a TF from CG enforce changes on WG? Specifically, looking at the Marking TF tasks that we defined I refer to:
> Establishing the representation of WoT like a brand identity at

Assume that the TF inside the WoT CG decides a new style from READMEs (which are inside repositories controlled by WoT WG) can we apply the changes without asking again for consensus inside the WG? or do we have to wait for another approval.... ?

**Comment by egekorkan** [comment]
Once the chairs of the WoT CG is fixed, we can discuss and define a collaboration "agreement" with the WoT WG/IG chairs.

**Comment by mmccool** [comment]
Seems this has been decided now :).  Or rather, there are some Marketing TF activities that should stay, some that should move, and we have to decide which.  Close this issue, open a new one to define collaboration points between WoT IG/WG and WoT CG?

**Comment by egekorkan** [comment]
Discussion continues at #288 , closing
