### ISSUE TITLE
Tasks of the Marketing TF

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#220]
For possible IG or CG discussion we should first clarify what the expected tasks of the marketing TF is. Based on the agreed tasks and requirements, we can be IG or CG.

**Comment by relu91** [comment]
> For possible IG or CG discussion

Linkin related issue: #219

**Comment by egekorkan** [comment]
Some not complete list of tasks I have thought of :
- Maintaining the web page
- Creating visual materials such as:
  - Powerpoint templates
  - Logo and Icons
  - Figures
  - Animation
  - Videos
- Establishing the representation of WoT like a brand identity at:
  - WoT repositories
  - WoT Web Page
  - WoT Wiki Pages
  - WoT Twitter account and other possible social channels
- Reaching out to the wide community through:
  - Social Media
  - Web Pages
  - Blog Posts
  - Promotional Text and Videos
  - Explainer Text and Videos
  - Tutorial Text and Videos
- Assuring consistent style for all the points above

**Comment by egekorkan** [comment]
Comments from Marketing call 16.11.2021:
- We are not allowed to create logos and icons, i.e. Marcomm team should do this, e.g. creating a logo for the TD

The work can be transferred to CG later on, we do not have to list these right now. However, after agreeing on this list, we can put this on the Marketing TF description.

**Comment by egekorkan** [comment]
This material can go into the Marketing Web Page. Once they are there, this issue can be closed.
