### ISSUE TITLE
Add Web Thing Protocol community group

### ISSUE THREAD

**Issue by relu91** [w3c/wot-marketing#224]
As discussed today, we should add [Web Thing Protocol Community group](https://www.w3.org/groups/cg/web-thing-protocol#:~:text=The%20mission%20of%20this%20group,use%20cases%2C%20requirements%20and%20specifications.) to the [Community page](https://www.w3.org/WoT/cg/). @benfrancis would you like to have something particular in the short description of the group?

**Comment by benfrancis** [comment]
This is great, thank you.

I think the description from the group home page is fine if it works for you, with one slight edit. The final URL of the Web Thing Protocol Community Group Charter is https://w3c.github.io/web-thing-protocol/charter/ (I couldn't figure out how to edit it on the home page).

I've noticed that the "join" links on that page prompt for a username and password, which is potentially confusing for new members. It might be useful to link to the home pages at https://www.w3.org/community/* instead.

Some useful links:

[Home Page](https://www.w3.org/community/web-thing-protocol/)
- [Charter](https://w3c.github.io/web-thing-protocol/charter/)
- [Mailing List](https://lists.w3.org/Archives/Public/public-web-thing-protocol/)
- [Participants](https://www.w3.org/community/web-thing-protocol/participants)
- [Use Cases & Requirements](https://w3c.github.io/web-thing-protocol/requirements/)

**Comment by egekorkan** [comment]
@benfrancis we have a template ready for new CG submission. Could you fill [this](https://github.com/w3c/wot-marketing/blob/main/docs/cg/template.html) and submit a PR to add it below of the CG page at https://github.com/w3c/wot-marketing/blob/main/docs/cg/index.html
