### ISSUE TITLE
Deleting Table of Contents looking section from Wiki pages

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#228]
I am not sure why there is an unrelated Table of Content looking section in each wiki page of task forces. This makes it difficult, especially on mobile, to scroll to the relevant content. This should not be on the wiki page of each task force but only in the main one. The part I mean is in the following, i.e. the section between the top title and the "Tuesdays ..." header.:
![image](https://user-images.githubusercontent.com/20195407/141974088-cf28a34d-3b19-48f6-9126-5f5e012a54e4.png)

**Comment by egekorkan** [comment]
In the marketing call of 16.11.2021:
- The WebConf Information can be simply a link to https://www.w3.org/WoT/IG/wiki/Main_Page#WebConf_Meetings
- Obsolete Calls can be removed from all TF Wikis
- Both of these points have to be discussed in the Main Call of 17.11.2021

**Comment by ashimura** [comment]
Based on the discussion during the [WoT call on 17 Nov. 2021](https://www.w3.org/2021/11/17-wot-minutes.html#t03), I've updated the ToC section accordingly. 
Please see the wiki pages, e.g. https://www.w3.org/WoT/IG/wiki/Main_WoT_WebConf .

**Comment by egekorkan** [comment]
Closing since it is done. Improvement of the initial part is tracked at #231
