### ISSUE TITLE
Have Regular CG Meetings - OpenDay

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-marketing#236]
It might be useful to schedule a regular "OpenDay", which could be a WoT CG event (to allow non-members to attend and present).

**Comment by egekorkan** [comment]
What needs to be done:

- [ ]  Change of the chair. Ege as initial candidate. To be discussed in the main call tomorrow.
- [ ]  Cleanup the current page
- [ ]  Point to the new website
- [ ]  (later) Generate content based on plugfests
- [ ]  Make openday an official CG activity. This implies changes to the CG charter.

**Comment by egekorkan** [comment]
@mmccool I think that the CG Meetups are happening already but no plans for it to become really regular. If you are interested in making it regular, please join the CG internal meeting on March 6. See https://www.w3.org/events/meetings/0b0a4962-9dba-4213-903a-582509710914/20230306T170000
