### ISSUE TITLE
Tools at Developers tab should be better organized

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#245]
Currently, the developers tab/page has different category of tools (or tool-like "stuff"). I think that this needs a better organization to identify where to use which tool. There are specific (single purpose) implementations under WoT implementations like sayWoT, WADE and also under TD Tooling with WoTify, shadow thing, test bench. 

From my point of view, we have the following categories:
1. "Low level" WoT libraries: Software libraries like node-wot, wot-py, sane, nodegen that allow you to build a custom WoT software
2. WoT Software with specific purposes: These are more less like executables (not really meant to be used as a dependency). Examples are Test Bench, sayWoT, shadow thing
3. TD Tooling or Helper tools: These are mostly hosted services, plugins to IDEs or specific software that help you to build WoT applications. Examples are TD Playground, Editdor, WAM, WADE, JDT
4. TDDs: Self explanatory.

I would like to get some feedback and start restructuring this page.

Note: Additionally, we should think of a policy on how to link these tools.

**Comment by danielpeintner** [comment]
I agree, the page can (and maybe should) be restructured.

I think a good exercise is to use the list we have so far and try to *put* it in your categories.

Note: besides the actual tools we also have links to slides/material etc. Not sure how we deal with those links. Maybe we should no longer link to such information.

> Note: Additionally, we should think of a policy on how to link these tools.

I am not 100% sure what you mean by that. Is a link, as we have it today, not sufficient?

**Comment by egekorkan** [comment]
> I am not 100% sure what you mean by that. Is a link, as we have it today, not sufficient?

This was mentioned by @ashimura in the previous call. I do not remember the exact point so @ashimura can you elaborate?

**Comment by egekorkan** [comment]
To be continued!

We want to categorize them into different categories and each category should explain what they do. A single tool can be listed in two places.

Categories:
1. TD Directory Implementations. Tags: Service
2. WoT Runtime Implementations. Tags: Library, CLI, Runtime. These are node-wot, wot-py, sane, nodegen
3. Development Tools. These are WADE, FXUI Tags: 
4. "Helpers". These are TD Code and WAM. We need a better name
5. TD Tooling. Tools to manipulate/edit TDs. Playground, Editdor, td-tools of node-wot, JDT
6. Software, Middleware: These are sayWoT!, shadow thing, testbench

**Comment by egekorkan** [comment]
I have updated the previous comment, please provide feedback on the naming of these categories

**Comment by thjaeckle** [comment]
I would even split the "WoT Runtime Implementations", e.g. in:
* WoT Thing Description providers
* WoT Thing Description consumers

Some tools may be in both categories (like node-wot).

The [Eclipse Ditto](https://www.eclipse.org/ditto/) project would be with its [WoT integration](https://github.com/eclipse/ditto/pull/1270) a pure "WoT TD provider".
As part of the WoT integration we added a Java module providing a Java API for:
* building TDs and TMs with a builder-based API (DSL) and e.g. converting the Java object to JSON
* parsing a TD from a JSON string and proving it as TD Java object

Such a API (without the capabilities to consume or provide TDs) would probably be another category, maybe just:
* WoT APIs

**Comment by danielpeintner** [comment]
I tend to think it gets difficult to split all tools properly. Maybe categorizing is a better approach?

What about having a list of the tools (as we have them today). Moreover, in the beginning of the page we could have a matrix (table) with the name of the tool (linking to the proper description below) and a ✔ for each category it supports.

Hence, we would just need to find a good list of categories
* consumer
* producer
* directory
* middleware
* dev tool, helper
* ...

Just to give you an idea (see https://en.wikipedia.org/wiki/Comparison_of_file_archivers#Operating_system_support that has such a table, for a different purpose of course)

**Comment by egekorkan** [comment]
Call of 12.04:
- We will have a matrix of categories with list of tools underneath. 
- We will have a list under that matrix where each tool mentions what categories it supports, like the Wikipedia table example above.

**Comment by egekorkan** [comment]
Forgot to close this one, it is fixed. A follow up issue is at #319
