### ISSUE TITLE
Web Conference Meetings need to be updated

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#246]
[Web Conference Meetings](https://www.w3.org/WoT/activities/general/#web-conference-meetings) is out-of-date

see https://www.w3.org/WoT/IG/wiki/Main_Page#WebConf_Meetings which should be up-to-date 

Differences:
* Chairs Call
* Arch Call
* Profile Call
* Editors Call, starting from next week
* More?

see  https://www.w3.org/WoT/IG/wiki/index.php?title=Main_Page&diff=next&oldid=12592

**Comment by danielpeintner** [comment]
Note: Alternatively we can simply point to the wiki instead of duplicating content. Any opinion?

**Comment by egekorkan** [comment]
Call of 25.01.2021

We have more or less 3 options:
1. Updating and keeping the webpage version and removing wiki while linking to the webpage
2. Removing the webpage version and keeping the wiki
3. Removing the current webpage version and the wiki and then integrating the W3C Calendar system

Resolution is a multi-step process:
1. @egekorkan updates the webpage
2. In the main call we ask people's opinion on removing the wikipage
3. (if wiki is OK to remove) Remove the table in the wiki and put a link to the webpage
4. Add the W3C Calendar into the webpage and maintain only that. @mmccool will check it

Below are some useful links about the W3C Calendar:
- Email from Philippe Le Hegaret: https://www.w3.org/Guide/meetings/organize.html
- Current (and empty) calendar of WoT WG: https://www.w3.org/groups/wg/wot/calendar
- A Readme on the W3C Calendar: https://github.com/w3c/calendar

**Comment by danielpeintner** [comment]
FYI: I asked whether there is a way to embed the W3C calendar on our page., see https://github.com/w3c/calendar/issues/79

**Comment by egekorkan** [comment]
Discussion continues on #268
