### ISSUE TITLE
External Developer links in new tab/window

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#247]
Some links on https://www.w3.org/WoT/developers/ open in a new window/tab, some don't.

I would argue all *external* links should use  
`target="_blank"`

see also https://github.com/w3c/wot-marketing/pull/244#issuecomment-1016574131

**Comment by egekorkan** [comment]
Yes I agree as well

**Comment by danielpeintner** [comment]
Note: we need to decide "what" we do with other links, e.g. the [WG](https://www.w3.org/WoT/wg/) site points to the [charter](https://www.w3.org/2020/01/wot-wg-charter.html) in the *same* window/tab etc.

**Comment by egekorkan** [comment]
Call of 08.02.2022: The group decides on having new tab links for all external links
