### ISSUE TITLE
Using W3C Calendar

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#268]
Continuation of https://github.com/w3c/wot-marketing/issues/246
We have 3 tasks: 
1. is to consolidate it into one place
2. is rendering our page (https://github.com/w3c/calendar/issues/79)
3. is managing invites (ical etc.)

A hacky alternative would be to open an email account and send invites to it, then display that accounts calendar publicly and render it. Interested parties can follow this account's calendar. Disadvantage here is that someone needs to manage this account in order to accept invites so that they show up in the calendar.

**Comment by mmccool** [comment]
I have now set up the W3C Calendar entries.  We should add a link to them from the events/calendar page and start investigating how we can pull updates or do a mashup.  Either of these links will work, as I listed the meetings under both the WG and the IG.  I suggest we use the WG link, though:
* https://www.w3.org/groups/wg/wot/calendar
* https://www.w3.org/groups/ig/wot/calendar
You might have to log in first.  Note the WebExes are not direct info like with my Outlook invites, but links to the relevant emails as in the Web page.  I also put in one paragraph descriptions of each group (copied from the wiki pages) and links to each wiki page.

**Comment by egekorkan** [comment]
The pages linked above are accessible without login so it should enable us to crawl it regularly for changes via github actions.

**Comment by danielpeintner** [comment]
I suggest to use a script that downloads the ICS file (i.e., https://www.w3.org/groups/wg/wot/calendar/export) and renders the calendar accordingly.

I wouldn't be surprised if there exists a *good* JS script in the *wild*. 
I found for example
* https://foss-notes.blog.nomagic.uk/2019/04/display-your-ics-calendar-on-your-website/
* https://github.com/luser/calendarview

The alternative would be (like @egekorkan suggested) to do a daily GitHub action creating the calendar statically.

**Comment by egekorkan** [comment]
I have also opened a related issue in the W3C Calendar: https://github.com/w3c/calendar/issues/91

**Comment by danielpeintner** [comment]
FYI: I played a bit around based on https://gitlab.nomagic.uk/popi/js_calendar_from_ics/-/tree/master/ and created a calendar for WoT.
see http://peintner.org/tmp/ics/

TODOs:
* add possibility to change timezone
* at the moment ICS file was downloaded to avoid CORS issues. In case of a W3C server it should be fine to just link to https://www.w3.org/groups/ig/wot/calendar/export

**Comment by egekorkan** [comment]
By the way, I have discovered something about the links of our calendar events:

Going to the calendar and clicking at the upcoming marketing call gives `https://www.w3.org/events/meetings/45cf6f40-47f5-42bc-92f9-62196c437568/20230418T073000` as the URL. The last part is the specific date. Omitting that (i.e. `https://www.w3.org/events/meetings/45cf6f40-47f5-42bc-92f9-62196c437568`) causes a redirect so that cannot be used. However, that last part can be generated. Still, I think that something in the direction of @danielpeintner proposal above makes more sense

**Comment by egekorkan** [comment]
We have talked about it a lot but never really documented the requirements we have:
1. Ability to change timezone and ideally show the timezone detected by the browser (currently done)
2. Show only the relevant portion of the week and day, i.e. do not show the weekend, do not show times where there are no meetings (like at night in European timezone)
3. Generate a link to the W3C Calendar page.
4. Nice to have: Indicate whether it is an IG or WG event.

**Comment by egekorkan** [comment]
Also see https://github.com/w3c/wot-marketing/pull/404 for a simple test

**Comment by lu-zero** [comment]
https://github.com/niccokunzmann/open-web-calendar this seems another possible alternative.

[here](https://open-web-calendar.hosted.quelltext.eu/calendar.html?url=https%3A%2F%2Fwww.w3.org%2Fgroups%2Fwg%2Fwot%2Fcalendar%2Fexport%2F) an example

The [demo page](https://open-web-calendar.hosted.quelltext.eu/) shows all the options we can set and it includes a time-zone selection beside using the browser information.

**Comment by danielpeintner** [comment]
Looks very promising 👍

I created https://github.com/w3c/wot-marketing/pull/495 with the timezone changer etc.
There are some downsides (see PR) but I think it is good enough!
