### ISSUE TITLE
WoT can contribute to sustainability (SDGs) by facilitating IoT interoperability

### ISSUE THREAD

**Issue by takuki** [w3c/wot-marketing#28]
**Problems:**

Sustainability, ESG and SDGs are hot topics lately. It would be great if WoT can be touted to be able to help achieve these goals.

**Requirements:**

WEF (World Economic Forum) discusses "[The effect of the Internet of Things on sustainability](https://www.weforum.org/agenda/2018/01/effect-technology-sustainability-sdgs-internet-things-iot/)".

IoT are said to have effects on society and on the UN's sustainable development goals (SDGs) in the following five SDGs.

* Industry, innovation, and infrastructure (25%)
* Smart cities and communities (19%)
* Affordable and clean energy (19%)
* Good health and well-being (7%)
* Responsible production and consumption (5%)

On the other hand, "interoperability" of devices and different IT back-ends are said two be the largest two barriers to scaling the successes.

**Solution Proposals:**

In the press release, we can refer to WEF report and claim WoT will contribute to achieve those goals by facilitating IoT interoperability.

**Comment by egekorkan** [comment]
Given that press release is done a long time ago, closing
