### ISSUE TITLE
WoT - Daylight Savings starts March 13

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#283]
Daylight Savings starts on March 13 in the US, which will affect the timing of our meetings.

Details:
https://www.w3.org/WoT/IG/wiki/Main_WoT_WebConf#Call_Logistics

TODO: update https://www.w3.org/WoT/activities/meetings/

**Comment by danielpeintner** [comment]
Re-open since we need to re-align it in some days again

**Comment by egekorkan** [comment]
/remind me to update the times again in 2 weeks

**Comment by danielpeintner** [comment]
Note: We need to update the times for Europe at least

**Comment by danielpeintner** [comment]
resolved by https://github.com/w3c/wot-marketing/pull/296
