### ISSUE TITLE
Update links to recently published documents

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#285]
Updates to come for https://www.w3.org/WoT/wg/

- [x] Web of Things (WoT) Thing Description 1.1, https://www.w3.org/TR/2022/WD-wot-thing-description11-20220311/ -->  fixed by https://github.com/w3c/wot-marketing/pull/298 and https://github.com/w3c/wot-marketing/pull/337

- [x] Web of Things (WoT) Architecture 1.1, https://github.com/w3c/wot-marketing/pull/343

- [x] Web of Things (WoT) Discovery, https://github.com/w3c/wot-marketing/commit/c1d48f3c064b84a3680ce988a32b84eb8b286be8 and https://github.com/w3c/wot-marketing/pull/351

- [x] Web of Things (WoT) Profile, https://github.com/w3c/wot-marketing/commit/14134de7b1b35f154d3a899e1a619f04bc336b15

Note: Web of Things (WoT): Use Cases and Requirements has been updated https://www.w3.org/TR/2022/NOTE-wot-usecases-20220307/ but there is no link to it -> fixed by https://github.com/w3c/wot-marketing/pull/298

**Comment by danielpeintner** [comment]
Note: I have been asked to update the Discovery link/infos but this happened already, see  

https://github.com/w3c/wot-marketing/commit/c1d48f3c064b84a3680ce988a32b84eb8b286be8

However, it does not properly mention which publication it is. I think it is the Third (it still says "First")..
* https://www.w3.org/TR/2022/WD-wot-discovery-20220810/
* https://www.w3.org/TR/2021/WD-wot-discovery-20210602/
* https://www.w3.org/TR/2020/WD-wot-discovery-20201124/

Shall I provide a PR for that?

**Comment by egekorkan** [comment]
@danielpeintner could you update the profile link now?
