### ISSUE TITLE
Adding "Edit this page"  button

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#299]
I see an "Edit this Page" button more and more on some community-oriented pages. It allows others to propose quick edits and shows a more open-source friendly image (in my opinion). I have found this: https://www.eeemil.com/guides/creating-an-edit-this-post-on-github-button/#

Any objections/opinions?

**Comment by egekorkan** [comment]
Solved via #301

**Comment by danielpeintner** [comment]
I think I stumbled over a minor issue I think we should fix.
It's about opening the GitHub link in a *new* window instead of the same window/tab.
