### ISSUE TITLE
Working Group page - short term

### ISSUE THREAD

**Issue by draggett** [w3c/wot-marketing#3]
What changes do we want in the short term for the Working Group page, and who can apply the updates?
* https://www.w3.org/WoT/WG/

**Comment by danielpeintner** [comment]
I think that the WG page content is OK.
Hence, no real pressure to update in the short term.

The only minor thing I noticed is a "News" header in the end of the page which we might want to remove... but this is minor.

On the long term the design/layout should be synchronized.

**Comment by danielpeintner** [comment]
I propose simplifying the tables of the deliverables by pointing to the latest document only (see below). 

  | Last Pubblication | W3C Recommendation
-- | -- | --
WoT Architecture | 16 May 2019 (Candidate Recommendation) | 1 August 2019
WoT Thing Description | 16 May 2019 (Candidate Recommendation) | 1 August 2019

If we have consensus I can work on a PR.

**Comment by danielpeintner** [comment]
Since the new website is due to go online shortly, short term points are no longer relevant.

@draggett please reopen if you think differently
