### ISSUE TITLE
Participants links do not point to correct pages

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#316]
Clicking at participants at https://www.w3.org/WoT/wg/ and https://www.w3.org/WoT/ig/ brings me to some kind of a home page of the group instead of the participants (https://www.w3.org/groups/wg/wot). They should be corrected

**Comment by danielpeintner** [comment]
While I agree that #317 fixes the issue that "Participants" does not link to the proper subpage.
Doing this change means that there is no link to the "root" page (e.g., https://www.w3.org/groups/wg/wot). Another solution would be to rename the link and keep the link as is... people can still navigate to the participants tab.

**Comment by egekorkan** [comment]
That would be also an alternative. What should the text be? Page at W3C or something like would seem weird since this is our page. I also don't know what the point of that page could be for an outsider
