### ISSUE TITLE
JSON Schema Case Study

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#329]
Me and @relu91 have been contacted by @jviotti from Postman about submitting a case study about how we use JSON Schema and what we gained from it. It will be then published in the JSON Schema space (blog). We are supposed to fill a template and they will actually take it and run it through editors.

An example: https://json-schema.org/blog/posts/tyler-technologies-case-study

Template: https://github.com/json-schema-org/community/blob/main/docs/case-studies/template.md

If it is complicated to submit it as W3C, I can also just submit it as "How W3C WoT uses JSON Schema".

CC @koalie

**Comment by koalie** [comment]
Great! Please submit it on behalf of the W3C WoT group(s). I'm happy to review anything, if you think it's helpful. Thank you.

**Comment by egekorkan** [comment]
Marketing Call of 05.07:
- We should collect what it is used for:
  - Describing data of devices
    - Using it for describing of semantics and structure of the data
    - Validation of payloads
    - Readable and writable payloads (operation input and output)
  - Validation of TD (and TMs)
    - Validation of extensions (protocol vocabularies)
  - We are generating https://www.w3.org/2019/wot/json-schema
- We should write it together and review it, i.e. involve the whole group. We will discuss it in the main call.

**Comment by egekorkan** [comment]
I have started writing this at hackmd at https://hackmd.io/@egekorkan/json-schema-wot . I will create a PR once it is somewhat consistently readable. Feel free to comment or ask me personally for a link that allows editing

**Comment by egekorkan** [comment]
@jviotti just to be sure, do we have to answer the questions or can we create a "story" ourselves? If we answer the questions, I guess someone from Postman or JSON Schema will write the actual "flowing" text

**Comment by jviotti** [comment]
Hey @egekorkan , 

Sounds very exciting! I'll take a closer look at the draft later today.

> just to be sure, do we have to answer the questions or can we create a "story" ourselves? If we answer the questions, I guess someone from Postman or JSON Schema will write the actual "flowing" text

Either works for us. Some people struggle with creating the story themselves, so we can get just the answers and build that ourselves. However, if you are able to articulate the story yourself, that's probably much better, as you would know how to tell it much better than us anyway!

**Comment by jviotti** [comment]
@egekorkan Not sure if I'm missing something from my side, but I don't seem to have enough permissions to comment on the HackMD document. I'm definitely signed-in on HackMD.

**Comment by egekorkan** [comment]
> @egekorkan Not sure if I'm missing something from my side, but I don't seem to have enough permissions to comment on the HackMD document. I'm definitely signed-in on HackMD.

I have no idea why this is the case. Everyone should be able to comment, even not signed in. I have added a test comment at "the standardization" word after opening the link in a private window. In order to comment, you first select the text. It is a bit counterintuitive :sweat_smile:

**Comment by jviotti** [comment]
@egekorkan I found it! My ad-blocker was hiding the comment section! 😞 Adding comments now

**Comment by egekorkan** [comment]
@jviotti have another look at the Hackmd file. I have answered your comments and added some new sections and extensions.

**Comment by jviotti** [comment]
Looks pretty good @egekorkan! Let me bounce it around with a few folks from JSON Schema too in case they have any other comments

**Comment by jviotti** [comment]
Hi @egekorkan , I left this around for a while to get time for people to review from our side. Everything looks good 👍 We'll be compiling a final draft case study doc over the next week and share it back here :tada:

**Comment by egekorkan** [comment]
Thanks @jviotti . Let us know if you need help with anything, we can also deliver flowing text for some parts.

**Comment by jviotti** [comment]
@egekorkan I have sent a WIP PR (https://github.com/json-schema-org/blog/pull/18) to the JSON Schema blog with what we have so far. We took your answers to the template questions and tried to tell a story around it that matches how previous case studies look like.

Please give it a read and let us know if you want anything to be changed, added or removed!

**Comment by egekorkan** [comment]
@mmccool @sebastiankb @ashimura @koalie @relu91 can you have a look at the blog post that @jviotti has prepared in https://github.com/json-schema-org/blog/pull/18 ? Here is a pdf that shows how it looks like when rendered:

https://github.com/json-schema-org/blog/files/9378105/How.the.W3C.Web.of.Things.brings.JSON.Schema.to.the.Internet.of.Things.JSON.Schema.Blog.pdf

**Comment by koalie** [comment]
> @mmccool @sebastiankb @ashimura @koalie @relu91 can you have a look at the blog post that @jviotti has prepared in [json-schema-org/blog#18](https://github.com/json-schema-org/blog/pull/18) ? Here is a pdf that shows how it looks like when rendered:
> 
> https://github.com/json-schema-org/blog/files/9378105/How.the.W3C.Web.of.Things.brings.JSON.Schema.to.the.Internet.of.Things.JSON.Schema.Blog.pdf

I made comments in the (I think!) last pull request. Hopefully my input is usable 🤞
Very good article! Thank you.

**Comment by Relequestual** [comment]
This has now been published: https://json-schema.org/blog/posts/w3c-wot-case-study
https://twitter.com/jsonschema/status/1587449920218349570

**Comment by egekorkan** [comment]
@Relequestual @jviotti thank you for the collaboration! We will close this issue now and we will reach out to you in a week to possibly get some statistics about it :partying_face:
