### ISSUE TITLE
Demos for TPAC 2022

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-marketing#332]
Need to organize demos for TPAC 2022.  Suggest they go here in an events/09.2022.Demos directory.  Thoughts?  Demos are not the same as plugfests; should be "known working".

For TPAC 2022, propose scheduling a 1h breakout session, with remote participants, so more like a sequence of short presentations.  Maybe 4 demos, 15m each (maybe more like 13m, to allow a few minutes for setup and intros).  Live demos need cameras, etc for remote participants.  Probably Wed right after our group calls, e.g. at 10am Pacific.

Candidate demos:
1. Michael McCool - Home Assistant/Conexxus demo (light, temp sensor, door scenario for retail) + Node-RED - remote
2. Philipp Blum - RIoT - on-site
3. Toumura - Discovery in Node-RED - remote/on-site being decided
4. Fady - Industrial sorting line - remote

* Need to clarify what features are being shown in each demo.  What are the "takeaways" from each demo?
* Should look for opportunities to combine

**Comment by egekorkan** [comment]
TPAC 2022 is over, propose closing
