### ISSUE TITLE
WoT Tutorial at w3schools.com

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#335]
I am wondering whether W3C drives https://www.w3schools.com.

It would be very beneficial to have a Web of Things tutorial at https://www.w3schools.com

**Comment by egekorkan** [comment]
Also see https://en.wikipedia.org/wiki/W3Schools

**Comment by danielpeintner** [comment]
Anyhow, having a tutorial at w3schools might be useful

**Comment by egekorkan** [comment]
Call of 09.08:
- They are private company so it would be helping their business. 
- MDN for example has a public commitee so they can be approached instead.
- Closing since it is difficult to even contact them
