### ISSUE TITLE
Rework TD 1.1 Explainer

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#340]
https://github.com/w3c/wot-marketing/pull/331 has been merged but I think it contains some minor bugs.

see rendered version under https://www.w3.org/WoT/documentation/explainers/td11.html

Some things I noticed 
* external links do not use `target=”_blank”` to open in new window/tab
* images stretch the full width etc.

![grafik](https://user-images.githubusercontent.com/11281461/185106736-60847a98-34f9-4246-a413-5d01c7fd3b14.png)

**Comment by danielpeintner** [comment]
Note: i think there are some problems with linking... there are 2 files
* `td11.html` and
* `td11.md`
From the documentation page i assume it links to the wrong one.

To be honest, I do not really understand which version (html or md) is correct.
I also strongly suggest to remove the out-dated one since it just causes confusion and problems as we see..

@egekorkan if you tell me what is the correct one I can look into and fix the issue.

**Comment by egekorkan** [comment]
Call of 08.11:
- We will link to the explainer at https://github.com/w3c/wot-thing-description/blob/main/explainer/Explainer11.md and delete the current explainer content.
