### ISSUE TITLE
Images in Explainer do not stretch properly

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#353]
We are linking to the Explainer from our documentation page.
see https://www.w3.org/WoT/documentation/explainers/td11

The site itself is somewhat broken since all images are way to large...

![grafik](https://user-images.githubusercontent.com/11281461/199690951-f00dcd24-6592-4cd5-9c1f-2c5316915973.png)

**Comment by egekorkan** [comment]
It must be my mistake when I was formatting these.

**Comment by danielpeintner** [comment]
I did take a look and it seems that the problem is that we have 2 files with the *same* name but different extension for `td11`. 
Locally `jekyll` in my case picks the version which renders images correctly... on the website it uses the *other* version.

I can provide a PR to fix that by removing one or the other. I think we ought to do so to avoid confusion in the future. 
May I ask which is the **correct** version? Both were updates mostly at the same time @egekorkan 

![grafik](https://user-images.githubusercontent.com/11281461/200543403-db0822ff-7589-4859-bec9-defc3be1b10b.png)

**Comment by egekorkan** [comment]
Closing, the work continues at #340

**Comment by egekorkan** [comment]
Call of 22.11, closing as this is not relevant anymore
