### ISSUE TITLE
WoT Mastodon Account

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-marketing#360]
Since the W3C is hosting its own Mastodon instance (w3c.social), I think it would be very cool if the WoT Working Group was also present there :)

This would of course mean that there is an additional platform to manage. However, since Mastodon and other social networks in the so-called Fediverse rely on the W3C Standard ActivityPub for communicating with each other, I think it would also serve as another great example for the potential of W3C standards. Furthermore, Mastodon should be easier to handle in terms of data protection regulations, making it easier to embed a timeline on the WoT website, for example.

The Twitter and the Mastodon account could also be fed the same or similar content with (manual) cross posting, reducing the required effort.

(Lastly, this would prepare us for the event that Twitter could become ... unavailable for some reason. Ahem.)

**Comment by relu91** [comment]
When I found out about W3C Mastodon, I had the same thought!! thank you for creating this issue, I'm definitely support this activity.

**Comment by egekorkan** [comment]
Probably even more relevant now given that some people are leaving Twitter. 

Just that we have currently a Twitter account created by W3C Marcomm where we have the right to post so this may lead to some questions regarding who has the rights to do all this. It would be good if all WoT related groups (WoT WG, WoT IG, WoT Japanese CG, WoT CG and WebThing Protocol CG) can use it equally by just agreeing on a couple rules.

**Comment by egekorkan** [comment]
Now see https://github.com/w3c/wot-marketing/issues/362#issuecomment-1512944592

**Comment by egekorkan** [comment]
Even more needed now due to https://[w3c.social](https://w3c.social/@w3cdevs/111018661803569521)/@w3cdevs/111018661803569521

**Comment by koalie** [comment]
> Just that we have currently a Twitter account created by W3C Marcomm where we have the right to post so this may lead to some questions regarding who has the rights to do all this. It would be good if all WoT related groups (WoT WG, WoT IG, WoT Japanese CG, WoT CG and WebThing Protocol CG) can use it equally by just agreeing on a couple rules.

+1 to creating a WoT mastodon account on the w3c.social instance. The about and server rules are available at <https://w3c.social/about>.

Please, do sign up!
From a private window (to be sure not to be authenticated in mastodon), go to <https://w3c.social/> and click “create account” on the right-hand side.
If for example you need a different account for Japanese, you'll need to do so again.

**Comment by JKRhb** [comment]
With [this Mastodon post](https://w3c.social/@w3c/111534700276754588) published by the main W3C account yesterday, joining Mastodon and moving away from Twitter/X probably has probably become even more relevant.

**Comment by egekorkan** [comment]
We have an account now, closing with success!
