### ISSUE TITLE
Update links at the Documentation Page

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#375]
The [documentation page](https://www.w3.org/WoT/documentation/) points to REC versions of the specifications. We should update them with the newest versions once they are released. We can also point to CR versions already. Any opinions?

**Comment by danielpeintner** [comment]
My personal opinion is to wait for REC publications before updating the links.

**Comment by egekorkan** [comment]
This is something to do now, along with all the publication links.
