### ISSUE TITLE
Update content of WoT wikipedia

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#4]
The content of the [WoT Wikipedia page](https://en.wikipedia.org/wiki/Web_of_Things) is quite outdated. 

@egekorkan would take care of it.

Please also check issue https://github.com/w3c/wot-architecture/issues/207

**Comment by egekorkan** [comment]
From a first run, I have identified the following:
* The history was stopping at 2014, I have added that W3C has 4 editor's drafts etc. However, we can add more by detailing the release date of the RECs?
* There is a very subjective architecture section that is mainly from the WoT book. How will we agree on what will be the content is difficult. The french version of the WoT does not contain such a section and I would be supporting to remove it in the english version as well. Instead we can show a reduced version of the W3C WoT Architecture but this would make it subjective as well. 
* The french version is indeed good and more objective than the english version.

**Comment by egekorkan** [comment]
This got taken caren of in the meantime, closing
