### ISSUE TITLE
Press release comments March 9

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#40]
The current [press release](https://w3c.github.io/wot-marketing/pressrelease-wot-rec.html) has 2 points I am not sure about.

1. It speaks about "the last two years"
    * do we want to limit the work to 2 years (the first workshop took place in 2014)
2. The text "human-&machine-readable data format" looks and reads a bit strange with the &

**Comment by koalie** [comment]
>     2\. The text "human-&machine-readable data format" looks and reads a bit strange with the &

I've changed this to: "human- and machine-readable data format"

Please, let me know if that does NOT work.
