### ISSUE TITLE
Press release feedback

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#41]
Here are some other possible improvements to some phrases in the press release:

1. **Current sentence in the press release:**
The WoT building blocks increase interoperability for IoT applications and reduce integration efforts and costs.
**Proposal for replacement:**
Such a common way to Thing's assets increase interoperability for IoT applications and reduce integration efforts and costs for different kind of IoT scenarios such as Thing-to-Cloud, Thing-to-Gateway, Thing-to-Thing, and retrofitting legacy systems. 
</this statement responds a little to the picture>

2. **Current sentence in the press release:**
Developers
WoT simplifies software development and service integration.
**Proposal for replacement:**
Developers and Engineers
WoT simplifies IoT engineering, software development, and service integration.

3. **Current sentence in the press release:**
Device vendors
WoT provides a mechanism to provide and document open APIs.
**Proposal for replacement:**
Device vendors
WoT provides a common mechanism to provide and document device's metadata and capabilities.

4. **Current sentence in the press release:**
Cloud platform and application vendors
WoT provides opportunities to provide support services and applications.
**Proposal for replacement:**
Cloud platforms and application vendors
WoT provides opportunities to simplify device and/or datapoint onboarding, simulating, and provide support services and application development.

**Comment by egekorkan** [comment]
Regarding point 3, I think what is currently meant is that WoT enables somewhat automatic documentation of APIs, which is something that every API provider does. I think it is important to keep this "API Documentation" perspective, since it is very relatable. My proposal would be:

WoT provides a common mechanism to provide and document devices' APIs using their metadata and capabilities.

**Comment by sebastiankb** [comment]
@koalie what do you think?

**Comment by koalie** [comment]
> @koalie what do you think?

I defer to your collective preference. I'll do an editorial pass as needed (e.g. to remove repetition of "provide")

**Comment by sebastiankb** [comment]
I think, it makes sense to include this changes for now.

**Comment by koalie** [comment]
Will do when my PR gets the additional review before merging.

**Comment by mmccool** [comment]
I do think "documentation" is an important use case that actually we need to write up in architecture, too.   And maybe it should be "documentation and validation".   This is basically OpenAPI's main use case, actually.

**Comment by koalie** [comment]
This only point from this issue that isn't moot is the first one:
> Current sentence in the press release:
> The WoT building blocks increase interoperability for IoT applications and reduce integration efforts and costs.
> Proposal for replacement:
> Such a common way to Thing's assets increase interoperability for IoT applications and reduce integration efforts and costs for different kind of IoT scenarios such as Thing-to-Cloud, Thing-to-Gateway, Thing-to-Thing, and retrofitting legacy systems.
> </this statement responds a little to the picture>

I personally think the addition of "scenarios such as Thing-to-Cloud, Thing-to-Gateway, Thing-to-Thing, and retrofitting legacy systems" is too technical and abstract. But I'll leave it to you to determine if the press release in its current state still needs this change.

**Comment by danielpeintner** [comment]
Issue can be closed right?

**Comment by koalie** [comment]
Yes, our [press release](https://www.w3.org/2020/04/pressrelease-wot-rec.html.en) went out on 2020-04-09.
