### ISSUE TITLE
Twitter Integration Rethinking

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#426]
Twitter now requires login to see anything at all. Thus, our twitter feed on the right is not loading. We should think of a solution.

**Comment by danielpeintner** [comment]
Grrr 🤔 I don't think there are that many solutions.

1. Tweak it that it still works (is this even possible?)
2. Remove the feed 
3. ???

**Comment by egekorkan** [comment]
Call of 11.07: We will wait a bit to see if there is anything changing, otherwise we should either remove or try to show the latest tweet automatically.

**Comment by egekorkan** [comment]
As of now, there is still no change. The code generated at https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FW3C_WoT&widget=Timeline still does not work

**Comment by egekorkan** [comment]
Closing for now since we have a process to check for new tweets and update the page with the latest accordingly.
