### ISSUE TITLE
Add Mastodon header image

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-marketing#472]
Currently, our [Mastodon account](https://w3c.social/@wot) does not have a header image...

<img width="593" alt="image" src="https://github.com/w3c/wot-marketing/assets/12641361/ff84860a-7c1f-484d-b829-ea91fabbdebe">

...in contrast to our [Twitter account](https://twitter.com/W3C_WoT):

<img width="666" alt="image" src="https://github.com/w3c/wot-marketing/assets/12641361/d6efa52d-2c03-47e3-aa2c-f14439766f4a">

Would it make to reuse the same image from Twitter also for Mastodon? This is only a minor suggestion but would give our account a somewhat more "polished"/"professional" look, IMHO.

**Comment by egekorkan** [comment]
@Citrullin given that the image is provided by you, is it fine to use it here as well (asked for Twitter at https://github.com/w3c/wot-marketing/issues/206)

**Comment by egekorkan** [comment]
We are now using the same one from Twitter, I hope it is fine for you @Citrullin .

**Comment by Citrullin** [comment]
> We are now using the same one from Twitter, I hope it is fine for you @Citrullin .

Sorry, didn't see it earlier. That's fine, no issue.
