### ISSUE TITLE
How to make external links accessible

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#473]
I stumbled of [this link](https://blog.pope.tech/2024/01/02/how-to-make-external-links-accessible/) that kind of seems to suggest that _all_ external links should open in the same tab.

We, in some cases, do open a new window.
I don't have a strong opinion. I just wanted to share it with you..

**Comment by egekorkan** [comment]
Call of 30.01: We have decided follow the advice of W3C to make sure that all links do not open a new tab/page. @danielpeintner will provide a PR.
