### ISSUE TITLE
Please elaborate

### ISSUE THREAD

**Issue by koalie** [w3c/wot-marketing#48]
In the press release, one of the bullets listing the products using the WoT solutions, lacks detail:
> Runtime systems by WoTPy (Python), SANE Web of Things Servient (Java);

What can we say to give a little bit of information on the purpose?

**Comment by sebastiankb** [comment]
WoTPy (Python) and SANE Web of Things Servient (Java) are WoT runtime implementations (like Eclipse node-wot). Alternative sentence can be

> further WoT runtime implementations are WoTPy (in Python) and SANE Web of Things Servient (in Java)
