### ISSUE TITLE
Update new marketing call slot on meetings page

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#488]
07:30 -08:00 America/New_York on Thursday

see https://www.w3.org/WoT/activities/meetings/

**Comment by danielpeintner** [comment]
Note: wiki is also wrong, see https://www.w3.org/WoT/IG/wiki/Marketing_WebConf

**Comment by egekorkan** [comment]
> Note: wiki is also wrong, see https://www.w3.org/WoT/IG/wiki/Marketing_WebConf

fixed now :)
