### ISSUE TITLE
Target audiences for WoT materials

### ISSUE THREAD

**Issue by draggett** [w3c/wot-marketing#5]
We would benefit from a short description of the target audiences we want to communicate with, what they can be expected to be looking for, and what messages we want to send them.
* Business people interested in the business proposition: what's the problem, why its important, and how we're addressing it.  Our materials need to be credible, rational and emotional (following Aristotle's [modes of persuasion](https://en.wikipedia.org/wiki/Modes_of_persuasion)).
* Technical people who are new to the Web of Things and would like to learn more, and to have an easy way to try it out; and to be able to get in touch with others in their situation
* Standards people who want to understand just what the WoT IG/WG are doing, the roadmap, and how to get involved

How do such people find their way through the W3C website, and how does that relate to what we want to do with the WoT pages?

**Comment by egekorkan** [comment]
From the call of 30.11.2021:
The group thinks that the website addresses the standards and technical people rather well. For the business people, do you think it is sufficient? If not, please reopen this issue.
