### ISSUE TITLE
sign-off from Members we cite?

### ISSUE THREAD

**Issue by koalie** [w3c/wot-marketing#50]
Do we have sign off from Siemens, Eclipse, IBM, Hitachi, Python, and Mozilla to use their names and what we [say about them](https://w3c.github.io/wot-marketing/pressrelease-wot-rec.html)?

**Comment by k-toumura** [comment]
Hi @koalie ,
I'm a one of developers of Node-RED Node Generator, which is mentioned at:
> Node-red, the well known IoT tool from IBM, includes a WoT extension to simplify the development of node-red nodes which started as a contribution by Hitachi as part of their W3C WoT participation;

I discussed with Node-RED and Node Generator project leads (@knolleary, @dceejay, @kazuhitoyokoi) about this, and made a refinement version:
> Node-RED, the well known low-code development tool from the OpenJS Foundation, supports the WoT Thing Description as part of the Node Generator project to simplify the development of Node-RED nodes, which started as a contribution by Hitachi as part of their W3C WoT participation;

And also, we'll share this with OpenJS marketing team.

**Comment by sebastiankb** [comment]
>Siemens Desigo CC, their flagship Building Management Station uses WoT to help easily integrate datapoints and functions from different IoT systems into the Desigo CC management station and from there to cloud systems;

It was agreed between W3C MarkCom and Siemens to make such a statement for the main text. The statement is derived from Siemens' testimonial.

**Comment by sebastiankb** [comment]
>Python

is a programming language like Java. I think, there is no need to sign-off something.

**Comment by sebastiankb** [comment]
> Eclipse Thingweb.node-wot

node-wot is developed under the umbrella of the [Eclipse Foundation](https://en.wikipedia.org/wiki/Eclipse_Foundation). Typically, such projects are named with the term "Eclipse". You can compare it with a RFC standard of IETF or a W3C standard. In addition, node-wot is driven by WoT members.
