### ISSUE TITLE
Establish meeting for developer outreach

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#52]
After the discussion in the plugfest call of 01.04.2020:

We want to set up a (weekly) meeting that anyone can join, where we introduce a concrete implementation and have sometimes meetings from non-W3C member developers. We decided to create this issue in order to collect some input. Please provide what kind of session you would like to see and whether you would like to collaborate to a session.

Some ideas for the content of these meetings:

- Have a 10 minutes tutorial on how to implement something that is recorded and shared. The rest of the time is for questions and developers talking about their experience. A concrete implementation can be developing a CoAP Thing with node-wot, developing a Consumer application with node-wot, Creating a simulation via Oracle IoT Cloud 
- A blank session where people come and talk about their WoT development experience.
- In addition to any above: Organizing presentations from WoT developers (like a conference) that also include non-W3C members.

**Comment by lmy441900** [comment]
That would be great. I'm a personal developer (not working on WoT these days), and I've been paying attention on the development of WoT specifications (mostly in WG & IG mailing lists), but unfortunately it's hard for me to understand what's actually going on through the minutes, issues, and PRs.

I'd suggest providing some introductory sessions first, which may include an overview of the whole WoT architecture, how to implement a "minimum viable product", etc. The spec documents are long and a little bit hard for me to get the full picture, so I'd like to hear your ideas and visions on WoT.

Then yes, developers who already gained experience on developing WoT products could share their views on how to correctly / securely implement a WoT product. (I guess most of them are companies and university researchers participating in the development of specs.)

**Comment by egekorkan** [comment]
From meeting of 15.11, this is happening in the WoT CG and we can close this. @lmy441900 please have a look at the CG which has office hours now: https://github.com/w3c/wot-cg/discussions/16 and https://www.w3.org/groups/cg/wot/calendar
