### ISSUE TITLE
Regular updates

### ISSUE THREAD

**Issue by draggett** [w3c/wot-marketing#6]
The WoT Marketing Task Force needs a plan for driving regular and timely updates to our pages in keeping with our mission for the Web of Things.

**Comment by sebastiankb** [comment]
please see https://github.com/w3c/wot-marketing/issues/7

**Comment by danielpeintner** [comment]
I don't think this issue is still relevant?

Updates to our pages is in work and we try to regular use the twitter feed as well.

Shall we close the issue?

**Comment by egekorkan** [comment]
Twitter and GH based website solves this I think, can be closed
