### ISSUE TITLE
Add Audio to Node-RED/Node-gen tutorial

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-marketing#62]
Add (English) audio to ppt master for node-gen tutorial and regenerate video.
PPT should be master, should have embedded audio and have auto-advance on, then we can generate video from that.  Using PPT as a master lets us edit it easily later, while a video can be viewed more easily by everyone.

**Comment by egekorkan** [comment]
@mmccool can you point to which presentation this was talking about? I remember this but not exactly

**Comment by k-toumura** [comment]
maybe [this one](https://www.w3.org/WoT/developers/wot_nodegen.mp4) (in [Developer Tools page of WoT webpage](https://www.w3.org/WoT/developers/)).

**Comment by egekorkan** [comment]
I see now. @k-toumura do you have plans to add audio? It would be weird to ask someone else to do voiceover for you so if you do not plan to add it, I propose to close the issue

**Comment by k-toumura** [comment]
I agree with you to close the issue for now, as I don't have enough time to add audio in the short term.

Alternatively, we could label the issue as "low priority" or something similar.

**Comment by egekorkan** [comment]
Call of 18.01: We have decided to close this issue
