### ISSUE TITLE
Landing page - long term

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#7]
We need to restructure the landing page. The requirements should be

- [ ] shorting the introduction text (a sub-page like "More Background" can provide more details) 
- [ ] [IG](https://www.w3.org/WoT/IG/) and [WG ](https://www.w3.org/WoT/WG/) pages should be sub-pages of a new landing page 
- [ ] use one (modern) design for all pages
- [ ] use one place for the latest news 
- [ ] provide a place for developer (links to tools, background about PlugFest/Hackatons, etc)
- [ ] provide a place for manger (links to use cases, WoT architectures, etc)
- [ ] a nice explain WoT video 
- [ ] ...  

 

There exists a good proposal from @mkovatsc and @danielpeintner as a starting point. Find the rendered version [here ](https://cdn.statically.io/gh/w3c/wot-marketing/53921a0d/proposals/new-wot-landing-page/sketch.html).

**Comment by egekorkan** [comment]
Regarding one place for the latest news, I would vote for something like twitter which can be embedded to any page easily (like any news component of a website template) but can be also used in Twitter to interact with the community directly. Some examples from W3C to show that is indeed possible: [Official W3C](https://twitter.com/w3c?lang=en), [CSS WG](https://twitter.com/css3?lang=en ), [TAG](https://twitter.com/w3ctag?lang=en)

**Comment by sebastiankb** [comment]
yes, twitter has a good cost-benefit ratio vs. writing long blog posts.

**Comment by danielpeintner** [comment]
I think we can close this issue since all topics are covered by other issues (most of them are resolved already).
@sebastiankb ?

**Comment by sebastiankb** [comment]
yes
