### ISSUE TITLE
Combine Home page with top level page.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-marketing#71]
The new landing pages and the old home page have overlapping information and cause confusion.

The contents of the old home page contains outdated information and should be archived.
We should merge all content that is still relevant with the new pages and provide it there.

**Comment by mmccool** [comment]
We should think in terms of common tasks (eg finding the schedule and webex for calls) and then make it easy to find this information.   But we can't just uplevel everything to the top page... instead we need task-oriented links, for example, like "Schedule" that links to a page with ALL the schedule information in one page.

**Comment by mmccool** [comment]
A page with a "Task force overview" would be helpful.   Maybe not at the very top level, but one link away.   A unified Calendar view would also be useful.

**Comment by egekorkan** [comment]
In the call of 9.2.2021, we have decided to close this issue since the TF overviews already exist.
