### ISSUE TITLE
Wiki redesign - Use Cases and Requirements 

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-marketing#77]
The redesigned Wiki page should support a broad spectrum of users and scenarios,
including the following:

1. A new user wants to understand which work is done in which TFs and quickly find the corresponding repo and reach out to the TF chair with a question

2. A potential industrial adopter wants to understand which companies are actively contributing and supporting this standard. 

3. TF chairs need to be able to provide a reference on the work they are doing to their management.

**Comment by danielpeintner** [comment]
Hi,

as discussed I started a *small* navigation redesign that tries to take into account the following comments
* besides groups we should mention task forces (at the moment navigation only exists)
* navigation contains all possible links under "more"
* add privacy and terms in footer

At the moment the idea is mainly to discuss the revised navigation 
see developer version https://danielpeintner.github.io/wot-marketing/

What is currently missing is the entire description/content about
* what are groups for and why do we have 3 of them
* content of task forces and the initial "intro" to find the right one

Before filling it with content I would like to get feedback whether the updated navigation is what people would like to see.
Note: please compare to the current status quo https://w3c.github.io/wot-marketing/

**Comment by egekorkan** [comment]
:+1: from my side!

**Comment by sebastiankb** [comment]
+1 also from my side. One additional idea can be to have information provided which Task Force group belongs to which group (IG and WG). However, this maybe gets overloaded.

**Comment by egekorkan** [comment]
No new comments, closing decision by the call of 30.11.21
