### ISSUE TITLE
Icon Set to be used for website

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#78]
At the moment we use SVG images from https://www.flaticon.com/ for our website (e.g., [IG Charter](https://image.flaticon.com/icons/svg/149/149345.svg), [Mailing List](https://image.flaticon.com/icons/svg/131/131155.svg), ... ).

These icons were taken from the initial design provided by @mkovatsc. Personally I do not have much experience with the flaticon platform/service and do have issues finding nicely *matching* icons we might need in the future.

Hence I propose to rethink which icon set we might want to use for the web presence. There are some possible choices like
* https://fontawesome.com/icons
* https://tablericons.com
* https://icons.theforgesmith.com
* ...

I propose to pick **one** which kind of guarantees a better visual match across different icons.
My personal favorite would be font-awesome.

**Comment by egekorkan** [comment]
Due to changes with flaticon availability, we have changed to fontawesome and until further notice we will stick with it. Closing
