### ISSUE TITLE
WoT Implementation needs to be listed or described in WG or IG page

### ISSUE THREAD

**Issue by takuki** [w3c/wot-marketing#8]
Currently, there does not seem to be information about WoT implementations.
This information should be made available.

**Comment by egekorkan** [comment]
As reference, the [Thing Description Implementation Report](https://w3c.github.io/wot-thing-description/testing/report.html) or [WoTify](https://wotify.org) can be used.

**Comment by sebastiankb** [comment]
definitely, when we have the new webpage the references should be provided there.

**Comment by egekorkan** [comment]
As discussed in the call of [31.10.2019](https://www.w3.org/2019/10/31-wot-marketing-minutes.html), once the website design is decided, we can include these references.

**Comment by sebastiankb** [comment]
we have a new webpage that provides this information
https://www.w3.org/WoT/developers/
