### ISSUE TITLE
New WoT WG page should be upper-compatible to the current one

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-marketing#84]
This is kind of related to Issue #70 but as I mentioned during the WoT Marketing call on Sep. 15, the [newly proposed WoT WG page](https://w3c.github.io/wot-marketing/wg/) should b upper-compatible o the [current WoT WG page](https://www.w3.org/WoT/WG/) and should include the following items too:
- [X] W3C logo at the ~~left~~ top
- [x] Tab menus at the top: Standards, Participate, Membership, About W3C
- [x] Mission
- [x] Getting involved: Wiki, Calls, Mailing list, TFs and Editor's drafts
- [ ] Testing: Implementation Report, Add Results, Update Report
- [x] Group details: Our Charter, Participants, How to Join?, Code of Conduct, Royalty Free Patent Policy
- [x] GitHub repo (wotwg), Privacy, Terms

Maybe we could omit some of the obsolete information, though.

**Comment by danielpeintner** [comment]
@ashimura I will check the items boxes once they are implemented.

**Comment by danielpeintner** [comment]
I see 1 open task
* Testing -> propose to create a "Testing" activity task force page and add the reports/results there

w.r.t. "Mission"
I believe the mission is stated on the entry page.   @ashimura  do you think this is sufficient as is?

**Comment by egekorkan** [comment]
Call of 19.04
- Everything other than testing is implemented and testing has its own specific issue now (#307)
