### ISSUE TITLE
Long term - Setup Living Website 

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-marketing#9]
During the call on Oct 2, we decided to move a first *living* website into the https://github.com/w3c/wot-marketing repo.

As starting point we can use the sketch I showed https://danielpeintner.github.io/wot-pages/.
The code can be found here: https://github.com/danielpeintner/wot-pages/tree/gh-pages

It uses [jekyll](https://jekyllrb.com/) website generator that is fully backed by github.io.
Hence we can simply move it to a `gh-pages` branch and the dynamic parts like navigation are properly rendered.

Note: since I put it under a subdirectory "wot-pages" in my private repo we might need to update  these links. Once an initial setup is done I can propose a PR.

@ashimura can you setup the initial `gh-pages` et cetera?

**Comment by ashimura** [comment]
These days we mainly use the master branch for the GitHub Pages site, so I've updated the setting for this "wot-marketing" repo as well for that configuration ("master" branch for GitHub Pages). Is that OK by you? Or do you need to use "gh-pages" branch, @danielpeintner ?

**Comment by danielpeintner** [comment]
Either way is fine.

If you can put a simple test there for now I will create a PR...

**Comment by danielpeintner** [comment]
@ashimura I am a bit unsure whether "master" is really the *right* place.

With the current configuration one can easily browse through pages that are not really meant to be rendered as website.

see https://w3c.github.io/wot-marketing/posts/
It renders an *internal* working directory.

A dedicated "gh-pages" branch makes it very clear *what* is rendered and *what* not.

What do you think?

**Comment by danielpeintner** [comment]
Another alternative I see is to use a dedicated subfolder like "`/website`" or so in `master`.

Any opinions?

**Comment by egekorkan** [comment]
I think having it in master is an easier option for others to contribute easier. As a side not, I don't know if you can have `/website` as the folder name. GitHub allows only `/docs` as said [here](https://help.github.com/en/articles/configuring-a-publishing-source-for-your-github-pages-site)

**Comment by danielpeintner** [comment]
`/docs` is fine also.

Having said that, I just want to prevent that any material of the repo is rendered as *a* website.

**Comment by sebastiankb** [comment]
@ashimura @draggett 
May I ask you what the status is? I think the short-term solution seems to fail (#2). I propose that we go directly to the long term solution asap. This should be discussed in tomorrow's marketing call.

**Comment by danielpeintner** [comment]
Discussions goes on in https://github.com/w3c/wot-marketing/issues/19

-->  close
