### ISSUE TITLE
Add Task Forces to WG and IG overview page

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-marketing#92]
I would like to provide a proposal based on the draft of the redesigned wiki pages at:
https://w3c.github.io/wot-marketing/
https://w3c.github.io/wot-marketing/wg/
https://w3c.github.io/wot-marketing/ig/

The draft in the current form gives the impression that the entire WoT activity is primarily a “two company activity”, since it does not provide any further insights about task forces, their mandate and what is going on in the groups.

I think it is important to communicate to the public the tasks/task forces and current work items and also acknowledge the contributions, commitment and involvement from other people and companies. 

Taking this into consideration, I recommend to provide more info about the TF, i.e. TF mandate, leads, deliverable(s), calls, meeting minutes directly on the corresponding WG/IG page.

The sequence of the items on the WG/IG page could be:

- Charter
- Task forces
- Participants
- Mailing List(s)
- How to Join

The task force section should contain the mandate and the deliverable(s) of the TF and point to the corresponding call page and github repo.

The “More” tab and the "Activities" tab could be eliminated, since the activities fall under the task forces of the corresponding working group/interest group.

I hope this proposal makes it easier for newcomers and interested parties to better understand W3C WoT.

**Comment by danielpeintner** [comment]
@mlagally do you think it is possible to attend one of our next marketing calls?

The reason why I am asking is that we go back and forth on the issue. In the call there was decided that under activities we can have all task forces (and describe the associated efforts).

The grouping of having working group, interest group and community groups comes from the W3C split. Moreover, I don't think that it is easily possible to draw the line for each task-force whether it belongs to WG, IG or CG.
Note: IF we where a task force belongs to I am perfectly fine with linking from each WG/IG/CG site to the given activity.

Having said that, I think it makes it much easier to discuss this in a *live* call.

**Comment by mlagally** [comment]
Hi @danielpeintner,
I very much agree that live calls are a much better way for discussing and resolving issues.

However unfortunately I'm shuffling around many things during my days, so I have to restrict the times I can dedicate to W3C WoT.
At the moment I have to prioritize my work on WoT Profile, architecture, use cases and thing descriptions and can only dedicate a bit of time to marketing when output is brought to the main call for review and approval.

In the current form the Wiki pages need some improvement before they can be approved.

**Comment by mlagally** [comment]
@sebastiankb 
I'm not sure this issue has been already discussed in the marketing calls, can you please clarify.

I created https://github.com/w3c/wot-marketing/pull/134 to address these concerns which I raised in mid November
and would appreciate if we can discuss it in the next marketing call.

**Comment by sebastiankb** [comment]
@mlagally 
yes we talked about the wiki page situation. Ege already spend some time on this topic (see #85). However, our first attention was about our new web presence with the animation video. This already took a huge afford and time as well as needed a close exchange with the W3 marketing team. Restructuring the TF wiki pages, which is mainly relevant for members, will be one of the next tasks and we would be happy to get some support. 

I have also the impression that there is an misunderstanding about the "wiki pages" like [Main wiki page](https://www.w3.org/WoT/IG/wiki/Main_Page) and the new [WoT page presence](https://www.w3.org/WoT/). Your PR is about the new web page. As you know, this PR is fine with me and I support this, we just need clarity on the TF assignments. To speed up this discussion, it would be great to comment on this in the PR.

**Comment by egekorkan** [comment]
The general architecture is in place. The missing TFs should create their content. @egekorkan is creating issues for the effected TFs.

**Comment by egekorkan** [comment]
@danielpeintner will add links to wikis while the TFs generate their content

**Comment by danielpeintner** [comment]
> @danielpeintner will add links to wikis while the TFs generate their content

see https://github.com/w3c/wot-marketing/pull/223
